### ISSUE TITLE
Saving an unpickled figure.

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#7902]
Trying to save an unpickled figure using `savefig` throws an 
`AttributeError: 'CallbackRegistry' object has no attribute 'callbacks' `

The issue is reproduced using the following code in python 2.7 (from WinPython2.7.10), Windows 8.1 (64bit), matplotlib 2.0.0

```
import matplotlib.pyplot as plt
import pickle

fig= plt.figure()
ax = fig.add_subplot(111)
ax.plot([9,8,7])

pickle.dump(fig, file('fig.pickle', 'w'))

plt.close("all")

fig_pickled1 = pickle.load(file('fig.pickle'))

plt.savefig(__file__+".png")

```

The traceback of the call to this is

```
Traceback (most recent call last):
  File "D:\Data\Computer\Entwicklung\python\test\SO_pickle_matplotlib.py", line 43, in <module>
    plt.savefig(__file__+".png")
  File "C:\WinPython\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\matplotlib\pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\WinPython\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\matplotlib\figure.py", line 1572, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "C:\WinPython\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 222, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "C:\WinPython\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\matplotlib\backend_bases.py", line 2163, in print_figure
    self.figure.dpi = dpi
  File "C:\WinPython\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\matplotlib\figure.py", line 416, in _set_dpi
    self.callbacks.process('dpi_changed', self)
  File "C:\WinPython\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\matplotlib\cbook.py", line 546, in process
    if s in self.callbacks:
AttributeError: 'CallbackRegistry' object has no attribute 'callbacks'

```

Using `plt.show()` instead of saving works fine; the figure is shown as expected.
Using `pickle.dump(fig, open('fig.pickle', 'wb'))` for pickling and `fig_pickled1 = pickle.load(open('fig.pickle', "rb"))` does not change the behaviour.
Also, moving the loading to a new file has no effect. 
Trying to save in other formats like `pdf` does not change anything.

**Comment by anntzer** [comment]
This was broken in Py2 only (Py3 works fine) in f4e9c6cf04322e3cf5e90d824c2b66dd2b73c298 (2.5y ago), when CallbackRegistry was converted into a new-style class.  Turning it back into an old-style class seems to fix the issue.

(PS: that was the worst bisect I ever did, with a dozen nonworking commits in the middle :/).

**Comment by ImportanceOfBeingErnest** [comment]
Is "turning it back into an old-style class" meant to be a hint to a workaround? (I have no idea what that means). Is there any workaround for python 2.7?

**Comment by ImportanceOfBeingErnest** [comment]
I seem to have found a way to get rid of the error, which involves changing the code inside `cbook.py`.

As seen from the traceback the problem seems to be that `CallbackRegistry.process()` from `cbook.py` is called without `CallbackRegistry` being initiated; therefore `self.callbacks` does not exist as an (empty) dictionary.

The trick can therefore be to add an attribute `callbacks` directly inside the `class CallbackRegistry(object)`:
```
class CallbackRegistry(object):
    callbacks = dict()
    def __init__(self):
        ....
```

It does not seem to have any negative effect. Does anyone think it'd do any harm?

**Comment by anntzer** [comment]
You have to change it to `class CallbackRegistry:` (without `(object)`).  Making `callbacks` a global dict is clearly ripe for bugs.

**Comment by anntzer** [comment]
Actually the fact that the code works at all on Py3 is due to a misdocumented feature of the pickle protocol.  See http://bugs.python.org/issue12290.

**Comment by tacaswell** [comment]
duplicate of https://github.com/matplotlib/matplotlib/issues/6048

**Comment by NelleV** [comment]
Fixed by #7914
