### ISSUE TITLE
dynamic_image.py + saving animation broken

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#14042]
### Bug report

**Bug summary**

Uncommenting the `ani.save("movie.mp4")` line of `examples/animation/dynamic_image.py` and running the example with mpl master fails with
```
Traceback (most recent call last):
  File "examples/animation/dynamic_image.py", line 35, in <module>
    ani.save("movie.mp4")
  File "lib/matplotlib/animation.py", line 1137, in save
    save_count_list = [a.save_count for a in all_anim]
  File "lib/matplotlib/animation.py", line 1137, in <listcomp>
    save_count_list = [a.save_count for a in all_anim]
AttributeError: 'ArtistAnimation' object has no attribute 'save_count'
```
whereas the movie would be correctly saved with mpl3.0.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 37
  * Jupyter version (if applicable): no
  * Other libraries:

**Comment by timhoffm** [comment]
Introduced by #13564.
