### PR TITLE
Fix colorbar setting without artist

### LINKED ISSUE #13963: Dataless colorbars break when updated
#13171 documented how to construct a colorbar "without an associated artist", via `fig.colorbar(cm.ScalarMappable(norm=norm, cmap=cmap), ax=ax)`.  It is also possible e.g. to update the colorbar via
```
sm = ScalarMappable(norm=norm, cmap=cmap)
fig.colorbar(sm)
<...>
sm.set_cmap("plasma")
```
(Although this is only documented in master, the recipe has existed for a while.)

But this got broken by #13234: one now gets
```
Traceback (most recent call last):
  File "lib/matplotlib/cbook/__init__.py", line 214, in process
    func(*args, **kwargs)
  File "lib/matplotlib/colorbar.py", line 1189, in on_mappable_changed
    self.update_normal(mappable)
  File "lib/matplotlib/colorbar.py", line 1230, in update_normal
    self.set_alpha(mappable.get_alpha())
AttributeError: 'ScalarMappable' object has no attribute 'get_alpha'
```

Indeed, the ScalarMappable class does not define get_alpha().  I think the solutions are either to make Colorbar.update_normal first check for whether such a method exists, or to add a dummy get_alpha() (always returning 1) to ScalarMappable.

Allowing myself to label as release critical (as a regression) but feel free to relabel if you disagree.

---

mpl master, arch linux, py3.7

### PR DESCRIPTION
**Pull request by dstansby**
Fixes #13963

### CODE REVIEW

**Comment by jklymak** [comment]
I dunno, I think if all the mappables tested in the test suite had a `get_alpha` method, then the base `ScalarMappable` method should have a `get_alpha` method

File: lib/matplotlib/cm.py [hunk 1]
```diff
@@ -325,6 +325,15 @@ def set_clim(self, vmin=None, vmax=None):
             self.norm.vmax = colors._sanitize_extrema(vmax)
         self.changed()
 
+    def get_alpha(self):
```
Comment (anntzer) [inline lib/matplotlib/cm.py]: Would leave a comment (not necessarily in the docstring) like "this method is intended to be overridden by Artist subclasses".
