### ISSUE TITLE
[Bug]: Inheriting from both FigureCanvasQTAgg and FuncAnimation no longer possible

### ISSUE THREAD

**Issue by berghaeu** [matplotlib/matplotlib#25856]
### Bug summary

`FigureCanvasQTAgg.__init__(self, mpl_fig.Figure())` gives `TypeError: FuncAnimation.__init__() missing 2 required positional arguments: 'fig' and 'func'`. Was working in matplotlib 3.5.2. Same Problem appears by using FigureCanvas.

### Code for reproduction

```python
import matplotlib.figure as mpl_fig
import matplotlib.animation as anim
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg

class SimulationPrevCanvas(FigureCanvasQTAgg, anim.FuncAnimation):
    def __init__(self, x:List, y:List) -> None:

     FigureCanvasQTAgg.__init__(self, mpl_fig.Figure())
```

### Actual outcome

```
    super().__init__()  # Typically the GUI widget init (if any).
TypeError: FuncAnimation.__init__() missing 2 required positional arguments: 'fig' and 'func'
```

### Expected outcome

Animated plot inside QT.

### Matplotlib Version

3.7

### Installation

conda

**Comment by timhoffm** [comment]
Are you sure, this worked before? `FuncAnimation.__init__()` has always required these two positional arguments.

One a  general note, multiple inheritance from Canvas and Animation seems quite adventurous. What is the motivation for this? Could this be solved with composition instead of inheritance?

**Comment by tacaswell** [comment]
I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/25685 in that pyside change to cooperative inheritance.

There must be some example someplace that does this if we now have 2 reports on this?

**Comment by berghaeu** [comment]
> I think this is a duplicate of #25685 in that pyside change to cooperative inheritance.
> 
> There must be some example someplace that does this if we now have 2 reports on this?

You are correct it really was a duplicate of #25685.
Seems like the problem was solvable by re-factoring how to use FigureCanvasQTAgg and anim.FuncAnimation inside Pyside 6.5. It seems to work that instead of inheriting use them as attributes:

`class SimulationPrevCanvas:
     def __init__(self, x: List, y: List) -> None:
        """
        :param x:       The data to init with at x axis.
        :param y:       The data to init with at y axis.
        """
        self.figure = mpl_fig.Figure()
        self.canvas = FigureCanvasQTAgg(self.figure)
        self.animation = anim.FuncAnimation(self.figure, self.time_update, fargs=(), interval=self.interval, blit=True)
`

**Comment by oscargus** [comment]
(Edited comment so that code rendered a bit better.)
