### ISSUE TITLE
pyparsing version 2.1.2 not supported (2.1.1 works though)

### ISSUE THREAD

**Issue by prinsherbert** [matplotlib/matplotlib#6399]
I used `setup.py install` today to install matplotlib in a venv. I got some rather hard to tackle tracebacks, as they were filled with exec's (meaning one can not see what the actual code is that fails).

Ultimately this was caused by pyparsing calling `.filename` and `.lineno` on a tuple (it obviously expected some kind of different object). But the tuple did contain a filename and a lineno as the first two elements, and some other stuff (the tuple seemed to be coming from the backtrace package). This code was wrapped in something like `if PY3: ...`

As a random guess I decided to downgrade pyparsing from 2.1.2 to 2.1.1, and this solved the problem. Unfortunately, I am not able to reproduce this anymore, even when upgrading pyparsing to 2.1.2. Still I though a heads-up might be in place, if someone seems `AttributeError: 'tuple' object has no attribute 'filename'` with a traceback that is more of less useless.

**Comment by jenshnielsen** [comment]
Duplicate of #6398 

It's not that pyparsing 2.1.2 is not supported by matplotlib it's that pyparsing 2.1.2 doesn't work with python 3.3/3.4 see https://sourceforge.net/p/pyparsing/bugs/95/
You can trigger the bug simply by importing pyparsing i.e. running the code below will trigger the bug

```
import pyparsing
```

**Comment by prinsherbert** [comment]
@jenshnielsen Thank you! I just wanted to make sure others would not go through the pain I went :)

**Comment by jenshnielsen** [comment]
No problem. It's unfortunate that this happens (A similar thing happened with 2.0.4 which had broken support for python 3 in general)

It's seems the pyparsing developer is aware of the issue so hopefully there will be a new release soon that pip will pick up.
