### ISSUE TITLE
Keyword argument error in Scatter Plot Sample Tutorial

### ISSUE THREAD

**Issue by guidocattani** [matplotlib/matplotlib#18413]
Tutorial Scatter Plot at 
https://matplotlib.org/3.3.1/tutorials/introductory/sample_plots.html#sphx-glr-tutorials-introductory-sample-plots-py

and

https://matplotlib.org/3.3.1/gallery/lines_bars_and_markers/scatter_demo2.html

gave an unexpected keyword argument error.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-ed0037b7a7be> in <module>
      4 # volume, adj_close from the mpl-data/example directory. The record array
      5 # stores the date as an np.datetime64 with a day unit ('D') in the date column.
----> 6 price_data = (cbook.get_sample_data('goog.npz', np_load=True)['price_data']
      7               .view(np.recarray))
      8 price_data = price_data[-250:]  # get the most recent 250 trading days

TypeError: get_sample_data() got an unexpected keyword argument 'np_load'

**Comment by jklymak** [comment]
Again, this works fine on 3.3.1.  Please use the version of the docs appropriate to your version of matplotlib.  Thanks...
