### ISSUE TITLE
updating to release 2.1.1 causes pip to stop working

### ISSUE THREAD

**Issue by machow** [matplotlib/matplotlib#10078]
### Bug report

**Bug summary**

Tested on Ubuntu 16.04. Using `apt-get install python3-matplotlib`, followed by `pip3 install matplotlib==2.1.1` causes any subsequent pip commands to raise the error..

```
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

Note that using `pip install matplotlib==2.1.0` works okay.

**Code for reproduction**

Below is a Dockerfile that reproduces the error. Note that it only breaks with the latest `pip` and `setuptools`...

```
FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y python3 python3-dev python3-pip python3-matplotlib \
    && pip3 install --upgrade pip setuptools \
    && pip3 list

RUN pip3 install matplotlib==2.1.1 && pip3 list
```

**Actual outcome**

Listed dependencies before updating matplotlib:

```
cycler (0.9.0)
matplotlib (1.5.1)
numpy (1.11.0)
Pillow (3.1.2)
pip (9.0.1)
pyparsing (2.0.3)
python-dateutil (2.4.2)
pytz (2014.10)
setuptools (38.2.4)
six (1.10.0)
wheel (0.29.0)
```

```
Step 3/3 : RUN pip3 install matplotlib==2.1.1 && pip3 list
 ---> Running in 66fa95928d38
Collecting matplotlib==2.1.1
  Downloading matplotlib-2.1.1-cp35-cp35m-manylinux1_x86_64.whl (15.0MB)
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from matplotlib==2.1.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/lib/python3/dist-packages (from matplotlib==2.1.1)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from matplotlib==2.1.1)
Requirement already satisfied: python-dateutil>=2.0 in /usr/lib/python3/dist-packages (from matplotlib==2.1.1)
Collecting cycler>=0.10 (from matplotlib==2.1.1)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.7.1 in /usr/lib/python3/dist-packages (from matplotlib==2.1.1)
Installing collected packages: cycler, matplotlib
  Found existing installation: cycler 0.9.0
    Uninstalling cycler-0.9.0:
      Successfully uninstalled cycler-0.9.0
  Found existing installation: matplotlib 1.5.1
    Uninstalling matplotlib-1.5.1:
      Successfully uninstalled matplotlib-1.5.1
Successfully installed cycler-0.10.0 matplotlib-2.1.1
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

**Comment by jenshnielsen** [comment]
It's usually a very bad idea to install a package from apt and then try to upgrade it with pip. Pip cannot uninstall the existing versions of either matplotlib, setuptools or pip so you probably end up with 2 competing versions of these packages. Why this seems to work with 2.1 and fails with 2.1.1 I don't know but the following which avoids install installing packages twice seems to work.

```
FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y python3 python3-dev python3-pip \
    && pip3 list

RUN python3 -c "from setuptools import setup, find_packages"
RUN pip3 install matplotlib==2.1.1 && pip3 list
```

But honestly you are probably better of isolating your pip installed packages from the system ones within a venv such as:

```
FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y python3 python3-dev python3-pip python3-venv \
    && pip3 list

RUN python3 -m venv myenv
RUN . ./myenv/bin/activate myenv \
    && python -m pip install --upgrade setuptools pip \
    && python -m pip install matplotlib==2.1.1 && pip3 list
```

**Comment by machow** [comment]
@jenshnielsen that's fair--it only occurs under pretty specific circumstances (apt-get install matplotlib, most recent versions of pip and setuptools). I ran into this issue while troubleshooting python course builds on DataCamp, and wanted to open it in case anyone runs into the same issue. 

This specific error seems to pop up from time to time with pip / setuptools. I'm happy to look into it a bit if anyone has any idea what changes between 2.1.0 and 2.1.1 may have produced it. Feel free to close if nots readily fixable on matplotlib's end :).

**Comment by tacaswell** [comment]
Going to close this as it is tied to crossing system-managed packages and pip-managed packages.  Definitely agree with @jenshnielsen there is likely fragments of 1.5.1 still floating around which are confusing pip.

I can not think of anything between 2.1.0 and 2.1.1 which changed anything about the packaging / handle namespace packages.   It may be worth raising this with the pypa folks as the traceback is entirely in `pip` (looks like they expected a list object and got a `_NamespacePath` object).
