### ISSUE TITLE
[Bug]: Axes divider not working when running API doc example

### ISSUE THREAD

**Issue by mptino** [matplotlib/matplotlib#28768]
### Bug summary

Running this sample code from the matplotlib API documentation leads to error: *AttributeError: 'Axes' object has no attribute '_axes_class'*

https://matplotlib.org/stable/gallery/axes_grid1/demo_colorbar_with_axes_divider.html

### Code for reproduction

```Python
import matplotlib.pyplot as plt

from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable

fig, (ax1, ax2) = plt.subplots(1, 2)
fig.subplots_adjust(wspace=0.5)

im1 = ax1.imshow([[1, 2], [3, 4]])
ax1_divider = make_axes_locatable(ax1)
# Add an Axes to the right of the main Axes.
cax1 = ax1_divider.append_axes("right", size="7%", pad="2%")
cb1 = fig.colorbar(im1, cax=cax1)

im2 = ax2.imshow([[1, 2], [3, 4]])
ax2_divider = make_axes_locatable(ax2)
# Add an Axes above the main Axes.
cax2 = ax2_divider.append_axes("top", size="7%", pad="2%")
cb2 = fig.colorbar(im2, cax=cax2, orientation="horizontal")
# Change tick position to top (with the default tick position "bottom", ticks
# overlap the image).
cax2.xaxis.set_ticks_position("top")

plt.show()
```

### Actual outcome

Traceback (most recent call last):
  File "/home/mptino/shapelets/shapelets/self_assembly/t.py", line 11, in <module>
    cax1 = ax1_divider.append_axes("right", size="7%", pad="2%")
  File "/home/mptino/.local/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 387, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/mpl_toolkits/axes_grid1/axes_divider.py", line 552, in append_axes
    ax = self.new_horizontal(size, pad, pack_start=False, **kwargs)
  File "/usr/lib/python3/dist-packages/mpl_toolkits/axes_grid1/axes_divider.py", line 486, in new_horizontal
    ax = self._get_new_axes(**kwargs)
  File "/usr/lib/python3/dist-packages/mpl_toolkits/axes_grid1/axes_divider.py", line 437, in _get_new_axes
    axes_class = axes._axes_class
AttributeError: 'Axes' object has no attribute '_axes_class'

### Expected outcome

See https://matplotlib.org/stable/gallery/axes_grid1/demo_colorbar_with_axes_divider.html

### Additional information

Works with matplotlib 3.7, FAILS with matplotlib 3.8+

### Operating system

Ubuntu

### Matplotlib Version

3.9.2

### Matplotlib Backend

qtagg

### Python version

3.10.12

### Installation

pip

**Comment by QuLogic** [comment]
It looks like you are running into #26827; the easiest way to fix that is to remove the system copy of Matplotlib so that it doesn't interfere with your venv. The harder fix is to petition your distro to stop shipping broken stuff.
