### ISSUE TITLE
[Bug]: Matplotlib and Herbie

### ISSUE THREAD

**Issue by jp2nyy** [matplotlib/matplotlib#29672]
### Bug summary

I am having an issue regarding MPL when using Herbie lately. This has been happening the past few weeks

### Code for reproduction

```Python
!pip install xarray matplotlib pygrib numpy pandas basemap cartopy metpy Herbie-data eccodes==2.38.3

from herbie import Herbie
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import numpy as np
import cartopy
import math
import metpy
from herbie.toolbox import EasyMap, pc, ccrs
from herbie import paint
import metpy.calc as mpcalc
```

### Actual outcome

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-96bd97320032>](https://localhost:8080/#) in <cell line: 0>()
      6 import math
      7 import metpy
----> 8 from herbie.toolbox import EasyMap, pc, ccrs
      9 from herbie import paint
     10 import metpy.calc as mpcalc

3 frames
[/usr/local/lib/python3.11/dist-packages/mpl_toolkits/axes_grid1/inset_locator.py](https://localhost:8080/#) in InsetPosition()
     16 @_api.deprecated("3.8", alternative="Axes.inset_axes")
     17 class InsetPosition:
---> 18     @_docstring.dedent_interpd
     19     def __init__(self, parent, lbwh):
     20         """

AttributeError: module 'matplotlib._docstring' has no attribute 'dedent_interpd'

### Expected outcome

The outcome expected is that it would run smoothly.

### Additional information

It have worked in 3.8.4 before I believe.

### Matplotlib Version

3.8.4

### Installation

pip

**Comment by WeatherGod** [comment]
For some reason, it looks like you have crossed installs of matplotlib. The
mpl_toolkits that's referenced in the traceback is probably old, or more
likely, has remnants of old files. Perhaps try to clear out the matplotlib
install and install it again?

**Comment by jklymak** [comment]
My guess is that you have an old mpl-toolkits you are loading.  Where is pip installing matplotlib?  

We strongly recommend the use of environments, either conda/mamba or pyenv.

**Comment by jp2nyy** [comment]
This is on Google Colab.

**Comment by tacaswell** [comment]
xref to the likely source of the problem: https://github.com/matplotlib/matplotlib/issues/26827#issuecomment-2185443923
