### ISSUE TITLE
Compile failure on win-amd64-py2.5

### ISSUE THREAD

**Issue by cgohlke** [matplotlib/matplotlib#937]
The latest github v1.1.x (and probably also the master) branch fails to build on win-amd64-py2.5 using the "Microsoft Platform SDK for Windows Server 2003 R2" compiler. Matplotlib 1.1.1rc was OK. 

```
X:\WinSDK52\Bin\Win64\x86\AMD64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DPY_ARRAY_UNIQUE_SYMBOL=MPL_ARRAY_API -DPYCXX_ISO_CPP_LIB=1 -I. -IX:\Python25-x64\include -IX:\Python25-x64\PC /Tpttconv/pprdrv_tt2.cpp /Fobuild\temp.win32-2.5\Release\ttconv/pprdrv_tt2.obj
pprdrv_tt2.cpp
ttconv\pprdrv_tt2.cpp(274) : error C2664: 'std::vector<_Ty>::vector(unsigned __int64,const _Ty &,const _A &)' : cannot convert parameter 1 from 'std::list<_Ty>::iterator' to 'unsigned __int64'
        with
        [
            _Ty=FlaggedPoint,
            _A=std::allocator<FlaggedPoint>
        ]
        and
        [
            _Ty=FlaggedPoint
        ]
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

error: command 'cl.exe' failed with exit status 2
```

Casting `points.begin()` and `points.end()`  from `std::list<FlaggedPoint>::iterator` to `std::vector<FlaggedPoint>::const_iterator` did not work.
