### ISSUE TITLE
BUG: PathCollection' object has no attribute 'set_sizes'

### ISSUE THREAD

**Issue by rougier** [matplotlib/matplotlib#3113]
The rain.py demo does not seem to work on 1.3.1.
I now gets:

```
File "rain.py", line 59, in update
    scat.set_sizes(rain_drops['size'])
AttributeError: 'PathCollection' object has no attribute 'set_sizes'
```
