### ISSUE TITLE
\overline and subscripts/superscripts in mathtext

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#5444]
The following code works fine in matplotlib 1.4.3, but it fails in matplotlib 1.5.0.

    import matplotlib.pyplot as plt
    ax = plt.subplot(111)
    ax.plot([0,1],[0,1])
    ax.text(0.5, 0.5, r'$\overline{\omega}$')
    ax.text(0.5, 0.6, r'$\overline{\omega}^x$')
    ax.text(0.5, 0.4, r'$\overline{\omega}_x$')

The traceback is super long, but here is the last line.

    File "/Users/Ben/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/mathtext.py", line 2809, in subsuper
      last_char.width = last_char._metrics.advance
    AttributeError: 'Vlist' object has no attribute '_metrics'

**Comment by QuLogic** [comment]
Bisect points to c56e56edfd880b9980a72a840da56dc4b958c9ba in #4873:
```
commit c56e56edfd880b9980a72a840da56dc4b958c9ba
Author: Víctor Zabalza <>
Date:   Sat Aug 8 21:10:44 2015 +0100

    improve integral and slanted nuclei placement
    
    clean up, remove unnecesary do_kern=False
    
    fix overunder
    
    make cm clearer at small sizes

:040000 040000 ae8dcc2837d034b327c80473543c026b8815cfc9 44fd9df88d3835179736217a9145167a519f6dc6 M	lib
```
CC @zblz

**Comment by zblz** [comment]
Well, that's embarrassing. We were definitely missing a test for a `Vlist` or `Hlist` as last character of the subsuper nucleus. I have added a fix against master in #5448, but should definitely be backported to 1.5.x.

**Comment by mdboom** [comment]
No worries.  The only people who never break code are people who never submit code ;)  Thanks for the quick fix.

**Comment by breedlun** [comment]
Slam, bam, thank you mam!  That was a quick turn-around.
