### PR TITLE
FIX: make sure nans are dealt with in path

### LINKED ISSUE #4252: Simplify handling of remote JPGs
Would it be possible to enhance Matplotlib to allow "im=imread(url)"
to work if url returns a JPG?

Currently (it seems):

* If the URL returns a PNG this works:
```
im = imread(urllib2.urlopen(url))
```
* If the URL returns a JPG, this DOESN'T work:
```
im = imread(urllib2.urlopen(url))
```
.. and neither does this:
```
im = imread(urllib2.urlopen(url),format='jpg')
```
... but this DOES work:
```
im = Image.open(cStringIO.StringIO(urllib.urlopen(url).read()))
```
See an example in Ipython Notebook here:
http://nbviewer.ipython.org/3918576/

So could just be hidden from the user so that "im = imread(url)" would
just work for JPG (assuming PIL was installed)?

### LINKED ISSUE #4525: masked arrays broken in py3k + gcc 5.1 on arch linux
This demo http://matplotlib.org/devdocs/examples/pylab_examples/color_by_yvalue.html is broken on python 3.

Only the left most plotted region is shown and happens either with ma arrays or `np.nan` filled arrays (have not started digging yet, I assume the eventually follow the same code path).  Filling with 0 works as expected.

I think bisect on this goes back to the cxx removal but many of the commits in there don't compile on python3 due to a numpy related gcc error so that isn't very helpful.

This smells like a subtle clipping bug.

attn @mdboom @efiring 

The most common compilation error is:

```python
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/home/tcaswell/.virtualenvs/dd_3k/lib/python3.4/site-packages/numpy/core/include -I/home/tcaswell/.virtualenvs/dd_3k/include/freetype2 -I/usr/local/include -I/usr/include -I. -I/home/tcaswell/.virtualenvs/dd_3k/include/python3.4m -c src/ft2font_wrapper.cpp -o build/temp.linux-x86_64-3.4/src/ft2font_wrapper.o
In file included from src/file_compat.h:7:0,
                 from src/ft2font_wrapper.cpp:3:
src/ft2font_wrapper.cpp: In function ‘PyObject* PyFT2Image_as_array(PyFT2Image*, PyObject*, PyObject*)’:
src/ft2font_wrapper.cpp:142:47: error: ‘PyArray_UBYTE’ was not declared in this scope
     return PyArray_SimpleNewFromData(2, dims, PyArray_UBYTE, self->x->get_buffer());
                                               ^
/home/tcaswell/.virtualenvs/dd_3k/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:129:46: note: in definition of macro ‘PyArray_SimpleNewFromData’
         PyArray_New(&PyArray_Type, nd, dims, typenum, NULL, \
                                              ^

```

Going to try rolling back to older versions of numpy te see if that fixes it.

For future reference, the output of bisect:

The first bad commit could be any of:

4a56cdadeb874fd959263fdb7af474c2416457f4
cfbf8d5225ac696cb2c3a8ae096911470074a5f8
339537d58374e8c2f7dd62299a9869d819956937
8dae8186c82f7243b819162d6eb1a64c1afeb379
6e19dac792a42e6cc0f68f2066248a35657673ff
a22596839a7eb31d9700822f2ae09f43c2b765ce
697b3ef37c044787b01344ca166a24d4da58345b
c5ab7474a02f16e75e1bbabcb7af5f7d72f6f847
5204635911f911a48c03ca3cf2f1f70341d396cf
af578f5f35b2d7fef36a35a50d156c027472a816
0624664f857f35583301f55553d28e00a4013770
6d0717930000cafeeecabed900ac1b286a4176da
ba4016014cb4fb4927e36ce8ea429fed47dcb787
d862c4740984433545461ded596d421f48f6b6a7
d8c1d0d5e494465cbc27a639d5337240d84997fe

We cannot bisect more!

Bisect Log:
git bisect start 'master' 'v1.4.3'
a165735 bad Merge pull request #4521 from jkseppan/issue-4475
21f46ff good REL : version 1.4.3

git bisect bad 056ba7a87e5bbd37dbf61a3c27329dc4f5648a54
056ba7a bad MNT : Remove ``NavigationToolbar2QTAgg``

git bisect bad 112f199e26a0ad2047e626f4ceea437196a75909
112f199 bad Merge pull request #3752 from astrofrog/rc_context_exceptions

git bisect good 34ed45af6c693d6951a82619bb669fc5463f4f9d
34ed45a good Merge pull request #3291 from joferkington/lightsource-enhancements

git bisect bad c6f24d3edc787303d631d62c74893bf9bcaaf152
c6f24d3 bad Merge pull request #3665 from jkseppan/fix-gdk-strides

git bisect good 0f4a68d3b75ae5ef192b1c90d876e18ff9de86c5
0f4a68d good Merge pull request #3547 from jkseppan/numpy-deprecation

git bisect bad 7891790ea379d5960fbd61f4667919519456a9a4
7891790 bad Remove reference to PyCXX

git bisect skip 697b3ef37c044787b01344ca166a24d4da58345b
697b3ef skip Restore parallel testing

git bisect skip 6d0717930000cafeeecabed900ac1b286a4176da
6d07179 skip Change how array converter functions are defined

git bisect good 7b206eb0eb150c9b3f8f451977055500c12d92ed
7b206eb good Skip shading of masked array test on numpy 1.6

git bisect skip 8dae8186c82f7243b819162d6eb1a64c1afeb379
8dae818 skip Remove some obsolete TODOs

git bisect skip af578f5f35b2d7fef36a35a50d156c027472a816
af578f5 skip Add .clang-format to repository

git bisect good ea8617d01daa63201d026688efd994423c54659c
ea8617d good fix E201 and E202 pep8 errors

git bisect skip 4a56cdadeb874fd959263fdb7af474c2416457f4
4a56cda skip Fix compilation

git bisect skip d862c4740984433545461ded596d421f48f6b6a7
d862c47 skip Fix Mac compile again

git bisect skip cfbf8d5225ac696cb2c3a8ae096911470074a5f8
cfbf8d5 skip Remove debugging prints

git bisect skip ba4016014cb4fb4927e36ce8ea429fed47dcb787
ba40160 skip Remove use of PyCXX in core C++ extensions

git bisect skip 339537d58374e8c2f7dd62299a9869d819956937
339537d skip Fix curve simplification

git bisect good dbeed94d578c458d31842cd13c04f665155986cb
dbeed94 good Merge pull request #3661 from jenshnielsen/numpy_16_fixes

git bisect skip 6e19dac792a42e6cc0f68f2066248a35657673ff
6e19dac skip Fix segfault on Python 3

git bisect skip 0624664f857f35583301f55553d28e00a4013770
0624664 skip Fix test_hexbin_pickable test

git bisect skip c5ab7474a02f16e75e1bbabcb7af5f7d72f6f847
c5ab747 skip More Python 3 fixes

git bisect skip a22596839a7eb31d9700822f2ae09f43c2b765ce
a225968 skip Documentation

git bisect skip 5204635911f911a48c03ca3cf2f1f70341d396cf
5204635 skip Windows-related fixes, thanks to @cgohlke

git bisect bad d8c1d0d5e494465cbc27a639d5337240d84997fe
d8c1d0d bad Remove usage of old Numpy API

### PR DESCRIPTION
**Pull request by tacaswell**
With gcc 5.1.0 it seems that the inner loop of the fast-path in
PathNanRemover gets optimized out of existence and the first non-finite
entry in the path prevents any further drawing.

This PR (rather hackishly) adds explicit de-references to x and y
to the loop to make sure the compiler does not decide it is unneeded.

Closes #4525

attn @efiring @mdboom @ianthomas23 I am in a bit over my head here (not that that has ever stopped me before).

### CODE REVIEW

**Comment by efiring** [comment]
Never having studied C++, I'm lost in this code.  I am guessing, however, that there is a cleaner solution involving a change in declarations somewhere--maybe 'volatile' modifiers or something like that.

**Comment by mdboom** [comment]
Wow.  Seems like a pretty bad compiler bug.  It can't possibly be optimizing that away on purpose.

You could try volatile, but I don't think that's related -- volatile is generally to indicate that a value may be altered by another thread (or interrupt handler) -- and the compiler won't let you alias the value with a non-volatile variable.  We're not multithreaded.  `register` might make sense, because it would force its loading into the CPU register, but my understanding is that `gcc` has ignored that for years on x86 anyway.  Though in the presence of an unknown bug, anything is possible, I suppose.  I think this fix is probably better than either of those options.

I can't reproduce on the 5.1.1 (which is what Fedora currently has -- it's actually a prerelease, since 5.1.1 hasn't been released yet), suggesting perhaps that the bug has already been fixed in the compiler and it's only a matter of time before others get this fix.  But it's not like your fix here is terribly horrible -- maybe add a comment that it's to get around an apparent compiler bug in gcc-5.1.0, since I'd be likely to come across this naively and think "um, no" and remove it.

BTW: It seems #4252 is the wrong bug, perhaps?

**Comment by mdboom** [comment]
Actually -- I take this back.  I *can* reproduce on 5.1.1-1 (Fedora prerelease) with Python 3.4.3.  I can't reproduce on 2.7.9.  So that's another data point (and also somewhat disturbing...)  I'll play with this for a bit.

**Comment by tacaswell** [comment]
should be #4525.

I am glad you can reproduce this.  I spent most of my evening yesterday and was getting worried I was making some really obvious mistake.

That it works in 2.7, but not with 3.4 is rather baffling.

**Comment by tacaswell** [comment]
@mdboom fyi, force pushed to fix the commit message.

**Comment by mdboom** [comment]
I think I've narrowed this down to the use of the `-fno-strict-aliasing` flag.  My Fedora-provided system Python 2.7.9 passes this flag to gcc when compiling extensions, and my self-compiled Python 3.4 does not.  (And adding the flag fixes it everywhere).  So the difference is not so much in the Python version but who it was configured/compiled.

I'm looking into whether we can fix our breaking of strict aliasing rules (the compile with `-fno-strict-aliasing` is raising some warnings), or we just forcibly add the flag (which gets tricky for non-gcc compilers).  Anyway, things are starting to make more sense, at least...

**Comment by tacaswell** [comment]
On both of my arch boxes there are 6-7 test failures that I have been ignoring because tests pass on travis, I should probably track those down to make sure none of these are due to similar things.

**Comment by mdboom** [comment]
The issue is here in `mpl_isnan.h`.  This macro is the core of all of the `MPL_isnan64`, `MPL_isfinite64` etc. macros.  Below, `u` is a double, and it gets recast as an `int64` in order to look at the individual bits and determine what special flags are set.

```
#if !defined(MPL_U64)
#define MPL_U64(u) (* (MPL_Int64 *) &(u) )
#endif /* MPL_U64 */
```

This kind of thing has had "undefined behavior" in C for a long time (forever?) but we could get away with it when compilers were less aggressive about optimizing.  And gcc's `-fno-strict-aliasing` has been a way to get the old behavior.

I think what we should do is move all of these to use the C++ stdlib's `isfinite`, `isnan` etc.  They should be just as fast, and inlined etc.  There may have been a portability issue with them back when John wrote matplotlib's macros (just guessing there) but I truly doubt that's an issue anymore.

I should have a net-negative-lines-of-code PR shortly.

**Comment by tacaswell** [comment]
Closing in favor of #4527
