### ISSUE TITLE
Cannot add colorbar to figure after pickle

### ISSUE THREAD

**Issue by Lnk2past** [matplotlib/matplotlib#19624]
### Bug report

**Bug summary**

After a figure has been pickled, a colorbar cannot be added to the figure and an exception is raised. I am sure there are other issues that more broadly cover this issue, but I am not sure of the extent of the problem(s).

**Code for reproduction**

```python
import pickle
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
pc = ax.scatter([1, 2, 3, 4, 5], [6, 7, 8, 9, 10], c=[0, 1, 2, 3, 4])

pickle.dump(fig, open('test.pkl', 'wb'))
fig.colorbar(pc, ax=ax)

plt.show()

```

**Actual outcome**

```
Traceback (most recent call last):
  File ".\pypresn\pypresn\test2.py", line 8, in <module>
    fig.colorbar(pc, ax=ax)
  File "C:\Users\Lnk2pas\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\figure.py", line 2207, in colorbar
    cax, kw = cbar.make_axes_gridspec(ax, **kw)
  File "C:\Users\Lnk2pas\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\colorbar.py", line 1519, in make_axes_gridspec
    layoutbox.nonetree(gs._layoutbox)
AttributeError: 'GridSpec' object has no attribute '_layoutbox'
```

**Expected outcome**

The figure should remain usable after being pickled and a colorbar can be added.

**Matplotlib version**

Tested on two systems:

```
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib; print(matplotlib.__version__)
3.1.0
>>> print(matplotlib.get_backend())
Qt5Agg
>>>
```

```
Python 3.7.1 (default, Dec 14 2018, 19:28:38)
[GCC 7.3.0] :: Anaconda Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib; print(matplotlib.__version__)
3.0.2
>>> print(matplotlib.get_backend())
Qt5Agg
>>>
```

I know that not everything inside of a figure can be pickled and so some things are discarded, but this renders the figure unusable in some ways (I am not familiar enough to know the extent of this). In the versions of MPL  am using, the issue seems to come from these lines:

https://github.com/matplotlib/matplotlib/blob/v3.3.1/lib/matplotlib/figure.py#L2129
https://github.com/matplotlib/matplotlib/blob/v3.0.2/lib/matplotlib/figure.py#L1915

I have not had a chance to try this on master to see how it changes, since it looks like the `__getstate__` method is a little different now.

**Comment by QuLogic** [comment]
This works fine in 3.3.4. Please update.

**Comment by Lnk2past** [comment]
Beat me to it, couldn't test master until getting home. Thanks for confirming
