### PR TITLE
Fix PathEffect rendering on some backends

### LINKED ISSUE #4024: Path effects applied to annotation text containing \n
I am using the following test program with mathplotlib 1.4.0 (via anaconda) on OS X 10.10.1:
```
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe

plt.subplot(1,1,1)
plt.annotate('line1\nline2',xy=(0.5,0.5),xycoords='axes fraction',fontsize='x-large',
	path_effects=[pe.withStroke(linewidth=1,foreground='r')])
plt.show()
```
This fails with:
```
AttributeError: GraphicsContextBase instance has no attribute 'draw_path'
```
Removing the \n from the text or removing the path_effects option both run as expected.  Any workarounds you can suggest are appreciated.

### LINKED ISSUE #5049: xkcd plots stopped working on Mac OS X.
The matplotlib xkcd example plots at 

http://matplotlib.org/examples/showcase/xkcd.html

stopped working with matplotlib 1.4.x (they used to work with earlier versions). This is with Python 2.7.5 on Mac OS X 10.9.5 and matplotlib 1.4.3.

The following Traceback is printed if I run one of the examples:

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/figure.py", line 1085, in draw
    func(*args)
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/lines.py", line 715, in draw
    drawFunc(renderer, gc, tpath, affine.frozen())
  File "/Library/Python/2.7/site-packages/matplotlib/lines.py", line 1072, in _draw_lines
    self._lineFunc(renderer, gc, path, trans)
  File "/Library/Python/2.7/site-packages/matplotlib/lines.py", line 1112, in _draw_solid
    renderer.draw_path(gc, path, trans)
  File "/Library/Python/2.7/site-packages/matplotlib/patheffects.py", line 115, in draw_path
    rgbFace)
  File "/Library/Python/2.7/site-packages/matplotlib/patheffects.py", line 217, in draw_path
    renderer.draw_path(gc, tpath, affine, rgbFace)
  File "/Library/Python/2.7/site-packages/matplotlib/backends/backend_macosx.py", line 58, in draw_path
    gc.draw_path(path, transform, linewidth, rgbFace)
AttributeError: GraphicsContextBase instance has no attribute 'draw_path'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/figure.py", line 1085, in draw
    func(*args)
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/axis.py", line 1119, in draw
    tick.draw(renderer)
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/axis.py", line 244, in draw
    self.tick1line.draw(renderer)
  File "/Library/Python/2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/lines.py", line 760, in draw
    rgbaFace)
  File "/Library/Python/2.7/site-packages/matplotlib/patheffects.py", line 127, in draw_markers
    **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/backend_bases.py", line 265, in draw_markers
    rgbFace)
  File "/Library/Python/2.7/site-packages/matplotlib/patheffects.py", line 115, in draw_path
    rgbFace)
  File "/Library/Python/2.7/site-packages/matplotlib/patheffects.py", line 217, in draw_path
    renderer.draw_path(gc, tpath, affine, rgbFace)
  File "/Library/Python/2.7/site-packages/matplotlib/backends/backend_macosx.py", line 58, in draw_path
    gc.draw_path(path, transform, linewidth, rgbFace)
AttributeError: GraphicsContextBase instance has no attribute 'draw_path'
```

### PR DESCRIPTION
**Pull request by mdboom**
The special sub-GC that is created by the PathEffectRenderer was of
GraphicsContextBase, rather than the backend-specific GC.

Fix #5049, Fix #4024 

Note that while this fixes the crashes in #5049, it does not mean that the sketch effect behind xkcd actually works in all backends -- that's more of a feature enhancement than a bugfix, because it never worked on all backends.

### CODE REVIEW

**Comment by mdboom** [comment]
~~This is a tricky one to test -- it all involves running backends we don't currently test on Travis.~~  Actually a PS test with a PathEffect would be sufficient, and wouldn't require installing anything special.

**Comment by tacaswell** [comment]
Might want to consider backing out #4201 and  #4542

**Comment by mdboom** [comment]
That's a good point, but I think #4201 and #4542 are unrelated, actually.  They are all part of the same cluster of bugs, but I don't think this would have fixed either of those.

**Comment by jkseppan** [comment]
The docstring of `backend_bases.py` calls `GraphicsContextBase` an "abstract base class" so it seems wrong to me that `RendererBase.new_gc` returns `GraphicsContextBase` instead of raising `NotImplementedError`, which would help us catch errors like this. Does any backend depend on this behavior?

**Comment by mdboom** [comment]
@jkseppan: That's a good point.  It does seem the Agg backend uses the `new_gc` from the base class, but none of the other renderers do.  I'd be happy to make the base `new_gc` `NotImplemented` and add an implementation to `RendererAgg`.

**Comment by tacaswell** [comment]
can we hold off on that bit of refactoring until 2.1?  Worried about (possibly vaporware) external backends which also rely on this.

**Comment by mdboom** [comment]
@tacaswell: Sure.  That makes sense.  It's not really a requirement that a renderer needs a custom GraphicsContext subclass to get things done, so it's quite possible some third-party ones don't and removing the base method would certainly break that.

**Comment by jkseppan** [comment]
I agree, this PR is a minimal bugfix and changing the method in the base class is an API change.

**Comment by mdboom** [comment]
Added a test.

File: lib/matplotlib/tests/test_backend_ps.py [hunk 1]
```diff
@@ -120,6 +121,16 @@ def test_composite_image():
         assert buff.count(six.b(' colorimage')) == 2
 
 
+@cleanup
+def test_patheffects():
+    with matplotlib.rc_context():
+        matplotlib.rcParams['path.effects'] = [patheffects.withStroke(linewidth=4, foreground='w')]
```
Comment (tacaswell) [inline lib/matplotlib/tests/test_backend_ps.py]: This line does not appease pep8

Comment (mdboom) [inline lib/matplotlib/tests/test_backend_ps.py]: Hopefully fixed now.

**Comment by tacaswell** [comment]
back-ported at ff2e4b923cb74d392c58dc9ce7b40dee034ae9ad
