### ISSUE TITLE
[Bug]: savefig pdf  produces AttributeError: module 'unicodedata2' has no attribute 'ucnhash_CAPI' with matplotlib 3.5.0

### ISSUE THREAD

**Issue by guidov** [matplotlib/matplotlib#21711]
### Bug summary

upgrading from matplotlib 3.4.3 to matplotlib 3.5.0

the save figure command produces an error when saving .pdf but not png

AttributeError: module 'unicodedata2' has no attribute 'ucnhash_CAPI'

Downgrading back to 3.4.3  and the problem disappears.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.savefig("figure.pdf")
```

### Actual outcome

```pytb

---> 84     plt.savefig("figure.pdf")

~/anaconda3/lib/python3.8/site-packages/matplotlib/pyplot.py in savefig(*args, **kwargs)
    956 def savefig(*args, **kwargs):
    957     fig = gcf()
--> 958     res = fig.savefig(*args, **kwargs)
    959     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    960     return res

~/anaconda3/lib/python3.8/site-packages/matplotlib/figure.py in savefig(self, fname, transparent, **kwargs)
   3010                         ax.patch._cm_set(facecolor='none', edgecolor='none'))
   3011 
-> 3012             self.canvas.print_figure(fname, **kwargs)
   3013 
   3014     def ginput(self, n=1, timeout=30, show_clicks=True,

~/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2312                 # force the figure dpi to 72), so we need to set it again here.
   2313                 with cbook._setattr_cm(self.figure, dpi=dpi):
-> 2314                     result = print_method(
   2315                         filename,
   2316                         facecolor=facecolor,

~/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py in wrapper(*args, **kwargs)
   1641             kwargs.pop(arg)
   1642 
-> 1643         return func(*args, **kwargs)
   1644 
   1645     return wrapper

~/anaconda3/lib/python3.8/site-packages/matplotlib/_api/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    384             # Early return in the simple, non-deprecated case (much faster than
    385             # calling bind()).
--> 386             return func(*inner_args, **inner_kwargs)
    387         arguments = signature.bind(*inner_args, **inner_kwargs).arguments
    388         if is_varargs and arguments.get(name):

~/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py in print_pdf(self, filename, dpi, bbox_inches_restore, metadata)
   2786             renderer.finalize()
   2787             if not isinstance(filename, PdfPages):
-> 2788                 file.finalize()
   2789         finally:
   2790             if isinstance(filename, PdfPages):  # finish off this page

~/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py in finalize(self)
    792         self.endStream()
    793         self._write_annotations()
--> 794         self.writeFonts()
    795         self.writeExtGSTates()
    796         self._write_soft_mask_groups()

~/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py in writeFonts(self)
    925                 chars = self._character_tracker.used.get(filename)
    926                 if chars:
--> 927                     fonts[Fx] = self.embedTTF(filename, chars)
    928         self.writeObject(self.fontObject, fonts)
    929 

~/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py in embedTTF(self, filename, characters)
   1422 
   1423         if fonttype == 3:
-> 1424             return embedTTFType3(font, characters, descriptor)
   1425         elif fonttype == 42:
   1426             return embedTTFType42(font, characters, descriptor)

~/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py in embedTTFType3(font, characters, descriptor)
   1150                 # the missing glyphs may not even be used in the actual string.
   1151                 warnings.filterwarnings("ignore")
-> 1152                 widths = [get_char_width(charcode)
   1153                           for charcode in range(firstchar, lastchar+1)]
   1154             descriptor['MaxWidth'] = max(widths)

~/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py in <listcomp>(.0)
   1150                 # the missing glyphs may not even be used in the actual string.
   1151                 warnings.filterwarnings("ignore")
-> 1152                 widths = [get_char_width(charcode)
   1153                           for charcode in range(firstchar, lastchar+1)]
   1154             descriptor['MaxWidth'] = max(widths)

~/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py in get_char_width(charcode)
   1141             def get_char_width(charcode):
   1142                 s = ord(cp1252.decoding_table[charcode])
-> 1143                 width = font.load_char(
   1144                     s, flags=LOAD_NO_SCALE | LOAD_NO_HINTING).horiAdvance
   1145                 return cvt(width)

~/anaconda3/lib/python3.8/site-packages/matplotlib/_text_helpers.py in warn_on_missing_glyph(codepoint)
     17         "Glyph {} ({}) missing from current font.".format(
     18             codepoint,
---> 19             chr(codepoint).encode("ascii", "namereplace").decode("ascii")))
     20     block = ("Hebrew" if 0x0590 <= codepoint <= 0x05ff else
     21              "Arabic" if 0x0600 <= codepoint <= 0x06ff else

AttributeError: module 'unicodedata2' has no attribute 'ucnhash_CAPI'
```

[@tacaswell edited to add markup]

### Expected outcome

Figure plotted

### Operating system

Ubuntu

### Matplotlib Version

3.5.0

### Matplotlib Backend

 module://matplotlib_inline.backend_inline

### Python version

3.8.12

### Jupyter version

3.2.4

### Installation

conda

**Comment by jklymak** [comment]
Please include a minimal example that triggers the error.  What you have shown works fine in 3.5.0 so you must have had something more in there (presumably some text).

**Comment by jiadong93** [comment]
> Please include a minimal example that triggers the error. What you have shown works fine in 3.5.0 so you must have had something more in there (presumably some text).

I also have this issue, minimal code below:

    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(1, 1, figsize=(7.2, 7.2))
    fig.savefig('test.pdf') 

error message says the same:

> module 'unicodedata2' has no attribute 'ucnhash_CAPI'

**Comment by jklymak** [comment]
We of course test that pdfs can be saved, and indeed I cannot reproduce this on master.  To my knowledge matplotlib doesn't require nor install `unicodedata2`.  Can you try from a fresh environment?

**Comment by tacaswell** [comment]
This error is coming out of the depths of CPython.  My guess that if you do

```python
chr(ord('a')).encode("ascii", "namereplace").decode("ascii"))
```

That will also fail (independent of Matplotlib).  It would be instructive to sort out which of those three calls (`chr`, `encode`, or `decode`) is the source of the problem.  It would also be very helpful if you could drop into a debugger and get the actual codepoint that is failing.  Annoyingly, it is failing in a print statement who's job it is to tell us which code point is failing else where.  Given the report of this failing with an empty figure, which should only include numbers as text, I also suspect that either your local installation is very broken (as the default font does not appear to contain [0-9]), you have a heavily customized `matplotlibrc`, or a more involved example is required to generate the issue.

It looks like `unicodedata2` is a backport library for updating the unicode data (https://pypi.org/project/unicodedata2/).  My guess is that on import it monkey-patches something and that is the source of the problem.  It looks like they commented this function out in their copy of `unicodedata.c` https://github.com/fonttools/unicodedata2/blob/44409e0c0cd5576378e7047f302a65617b767aa8/unicodedata2/unicodedata.c#L1377-L1380 .  Not being able to reproduce this it is impossible to be 100% sure, but I think it is more than likely that this is a bug in `unicodedata2` and should be reported to them.

**Comment by greglucas** [comment]
Just to add another data point here. I've been seeing a similar issue with unicodedata2 on some of the Cartopy test runners as well with not being able to import `unicodedata`.
https://github.com/SciTools/cartopy/runs/4290881148?check_suite_focus=true

I'm not able to reproduce locally with just matplotlib installed though, so I'm wondering if this is an issue with some conda package conflicts...

**Comment by QuLogic** [comment]
The Cartopy logs show:

> ```
> E       return f'{abs(longitude):{num_format}}\N{Degree Sign}{hemisphere}'
> E              ^
> E   SyntaxError: (unicode error) \N escapes not supported (can't load unicodedata module)
> ```

That isn't even in Matplotlib, so the issue is on a much deeper level and there's not really anything we can do about this.

**Comment by jiadong93** [comment]
thanks, it seems this is not a matplotlib issue, I updated some packages, the issue is gone now.

**Comment by jklymak** [comment]
Perhaps it would be helpful to identify which packages are using `unicodedata2` and report to them?  Certainly if they are using Matplotlib 3.x they cannot be using python2 anymore.

**Comment by jiadong93** [comment]
Sorry, I come to this thread again. The issue is still there TODAY. It is gone yesterday after updating... Now I am confused now.

**Comment by jiadong93** [comment]
> Downgrading back to 3.4.3 and the problem disappears.

@guidov , rolling back to 3.4.3 completely solved your issue?

**Comment by dopplershift** [comment]
For clarity, Matplotlib 3.5 is introducing the installation of unicodedata2 because we now depend on fonttools, which requires unicodedata2 on Python <=3.8.

I'm currently investigating issues with sphinx-gallery running examples (failing with `SyntaxError: (unicode error) \N escapes not supported (can't load unicodedata module)`) with something like `ax.set_label('\n{DEGREE FAHRENHEIT}')`. Unsure if these are related yet.

**Comment by jiadong93** [comment]
thanks, @dopplershift , I am considering rolling back matplotlib 3.4. Hope this can be fixed soon. It seems the issue only appears after I load some of my own modules. Not sure what has been changed. After that, even when I run minimal examples above, the issue persists. If we run freshly from minimal examples, it seems we don't have this issue.

**Comment by dopplershift** [comment]
If you can narrow down what `import` statement leads to your minimal examples failing, that may be helpful. I haven't been able to reproduce this outside sphinx yet.

**Comment by dopplershift** [comment]
@jiadong93 I've run down my problem and it's introduced through `charset_normalizer`--a buggy version is currently pinned by requests 2.26.0 from conda-forge. Not sure if any of that is relevant to you, but it might help.

**Comment by jiadong93** [comment]
@dopplershift , thanks for your info. I am unable to locate the issue quickly as I imported tons of my own modules before that. I will report to this thread as long as I get something useful.

**Comment by guidov** [comment]
yes rolling back completely solved my issues.

Sorry I don't have time to look into this with all of you.

**Comment by greglucas** [comment]
It looks like this should be fixed upstream now (thanks to @dopplershift!) so the solution is to upgrade the packages in your conda environment, specifically the requests package from conda-forge. If you are still getting this error after that, feel free to reopen.
