### ISSUE TITLE
masked arrays broken in py3k + gcc 5.1 on arch linux

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#4525]
This demo http://matplotlib.org/devdocs/examples/pylab_examples/color_by_yvalue.html is broken on python 3.

Only the left most plotted region is shown and happens either with ma arrays or `np.nan` filled arrays (have not started digging yet, I assume the eventually follow the same code path).  Filling with 0 works as expected.

I think bisect on this goes back to the cxx removal but many of the commits in there don't compile on python3 due to a numpy related gcc error so that isn't very helpful.

This smells like a subtle clipping bug.

attn @mdboom @efiring 

The most common compilation error is:

```python
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/home/tcaswell/.virtualenvs/dd_3k/lib/python3.4/site-packages/numpy/core/include -I/home/tcaswell/.virtualenvs/dd_3k/include/freetype2 -I/usr/local/include -I/usr/include -I. -I/home/tcaswell/.virtualenvs/dd_3k/include/python3.4m -c src/ft2font_wrapper.cpp -o build/temp.linux-x86_64-3.4/src/ft2font_wrapper.o
In file included from src/file_compat.h:7:0,
                 from src/ft2font_wrapper.cpp:3:
src/ft2font_wrapper.cpp: In function ‘PyObject* PyFT2Image_as_array(PyFT2Image*, PyObject*, PyObject*)’:
src/ft2font_wrapper.cpp:142:47: error: ‘PyArray_UBYTE’ was not declared in this scope
     return PyArray_SimpleNewFromData(2, dims, PyArray_UBYTE, self->x->get_buffer());
                                               ^
/home/tcaswell/.virtualenvs/dd_3k/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:129:46: note: in definition of macro ‘PyArray_SimpleNewFromData’
         PyArray_New(&PyArray_Type, nd, dims, typenum, NULL, \
                                              ^

```

Going to try rolling back to older versions of numpy te see if that fixes it.

For future reference, the output of bisect:

The first bad commit could be any of:

4a56cdadeb874fd959263fdb7af474c2416457f4
cfbf8d5225ac696cb2c3a8ae096911470074a5f8
339537d58374e8c2f7dd62299a9869d819956937
8dae8186c82f7243b819162d6eb1a64c1afeb379
6e19dac792a42e6cc0f68f2066248a35657673ff
a22596839a7eb31d9700822f2ae09f43c2b765ce
697b3ef37c044787b01344ca166a24d4da58345b
c5ab7474a02f16e75e1bbabcb7af5f7d72f6f847
5204635911f911a48c03ca3cf2f1f70341d396cf
af578f5f35b2d7fef36a35a50d156c027472a816
0624664f857f35583301f55553d28e00a4013770
6d0717930000cafeeecabed900ac1b286a4176da
ba4016014cb4fb4927e36ce8ea429fed47dcb787
d862c4740984433545461ded596d421f48f6b6a7
d8c1d0d5e494465cbc27a639d5337240d84997fe

We cannot bisect more!

Bisect Log:
git bisect start 'master' 'v1.4.3'
a165735 bad Merge pull request #4521 from jkseppan/issue-4475
21f46ff good REL : version 1.4.3

git bisect bad 056ba7a87e5bbd37dbf61a3c27329dc4f5648a54
056ba7a bad MNT : Remove ``NavigationToolbar2QTAgg``

git bisect bad 112f199e26a0ad2047e626f4ceea437196a75909
112f199 bad Merge pull request #3752 from astrofrog/rc_context_exceptions

git bisect good 34ed45af6c693d6951a82619bb669fc5463f4f9d
34ed45a good Merge pull request #3291 from joferkington/lightsource-enhancements

git bisect bad c6f24d3edc787303d631d62c74893bf9bcaaf152
c6f24d3 bad Merge pull request #3665 from jkseppan/fix-gdk-strides

git bisect good 0f4a68d3b75ae5ef192b1c90d876e18ff9de86c5
0f4a68d good Merge pull request #3547 from jkseppan/numpy-deprecation

git bisect bad 7891790ea379d5960fbd61f4667919519456a9a4
7891790 bad Remove reference to PyCXX

git bisect skip 697b3ef37c044787b01344ca166a24d4da58345b
697b3ef skip Restore parallel testing

git bisect skip 6d0717930000cafeeecabed900ac1b286a4176da
6d07179 skip Change how array converter functions are defined

git bisect good 7b206eb0eb150c9b3f8f451977055500c12d92ed
7b206eb good Skip shading of masked array test on numpy 1.6

git bisect skip 8dae8186c82f7243b819162d6eb1a64c1afeb379
8dae818 skip Remove some obsolete TODOs

git bisect skip af578f5f35b2d7fef36a35a50d156c027472a816
af578f5 skip Add .clang-format to repository

git bisect good ea8617d01daa63201d026688efd994423c54659c
ea8617d good fix E201 and E202 pep8 errors

git bisect skip 4a56cdadeb874fd959263fdb7af474c2416457f4
4a56cda skip Fix compilation

git bisect skip d862c4740984433545461ded596d421f48f6b6a7
d862c47 skip Fix Mac compile again

git bisect skip cfbf8d5225ac696cb2c3a8ae096911470074a5f8
cfbf8d5 skip Remove debugging prints

git bisect skip ba4016014cb4fb4927e36ce8ea429fed47dcb787
ba40160 skip Remove use of PyCXX in core C++ extensions

git bisect skip 339537d58374e8c2f7dd62299a9869d819956937
339537d skip Fix curve simplification

git bisect good dbeed94d578c458d31842cd13c04f665155986cb
dbeed94 good Merge pull request #3661 from jenshnielsen/numpy_16_fixes

git bisect skip 6e19dac792a42e6cc0f68f2066248a35657673ff
6e19dac skip Fix segfault on Python 3

git bisect skip 0624664f857f35583301f55553d28e00a4013770
0624664 skip Fix test_hexbin_pickable test

git bisect skip c5ab7474a02f16e75e1bbabcb7af5f7d72f6f847
c5ab747 skip More Python 3 fixes

git bisect skip a22596839a7eb31d9700822f2ae09f43c2b765ce
a225968 skip Documentation

git bisect skip 5204635911f911a48c03ca3cf2f1f70341d396cf
5204635 skip Windows-related fixes, thanks to @cgohlke

git bisect bad d8c1d0d5e494465cbc27a639d5337240d84997fe
d8c1d0d bad Remove usage of old Numpy API

**Comment by tacaswell** [comment]
but one of my co-workers can not reproduce this

**Comment by ericdill** [comment]
I am not seeing the same bug. I am running current master

```
$ git describe
v1.4.3-1752-g62bef78
```

with python 3
```
$ python --version
Python 3.4.3 :: Continuum Analytics, Inc.

$ ipython -c "import matplotlib; print('version = %s' % matplotlib.__version__); print('file = %s' % matplotlib.__file__)"
version = 1.5.dev1

file = /home/edill/dev/python/matplotlib/lib/matplotlib/__init__.py
```

and gcc 4.9.2

```
$ gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and numpy 1.9.2
```
$ ipython -c "import numpy; print('version = %s' %  numpy.__version__)"
version = 1.9.2
```

**Comment by ericdill** [comment]
Oh, right. And the output from running
```python
# use masked arrays to plot a line with different colors by y-value
from numpy import logical_or, arange, sin, pi
from numpy import ma
from matplotlib.pyplot import plot, show

t = arange(0.0, 2.0, 0.01)
s = sin(2*pi*t)

upper = 0.77
lower = -0.77


supper = ma.masked_where(s < upper, s)
slower = ma.masked_where(s > lower, s)
smiddle = ma.masked_where(logical_or(s < lower, s > upper), s)

plot(t, slower, 'r', t, smiddle, 'b', t, supper, 'g')
show()
```
is:

![screenshot from 2015-06-14 19 03 30](https://cloud.githubusercontent.com/assets/6223243/8150882/a69c5680-12c9-11e5-9953-d287ed02913a.png)

**Comment by efiring** [comment]
I'm seeing the same thing as @ericdill.

**Comment by tacaswell** [comment]
```
19:10 $ python --version
Python 3.4.3 :: Continuum Analytics, Inc.
```

```
19:13 $ gcc --version
gcc (GCC) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I get this behavior with two diffenent Arch Linux boxes with both numpy 1.9.2 and 1.8.2 

On a ubuntu box I get the expected behavior (gcc 4.9.2).

It does not work with system python + pip-installed almost everything on arch.

**Comment by tacaswell** [comment]
The other fun thing about this is that as I pan what ever the left-most line segment is, is what is shown.

I am seeing warnings like:

```
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_backends__backend_agg_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/home/tcaswell/.virtualenvs/dd_3k/lib/python3.4/site-packages/numpy/core/include -I/home/tcaswell/.virtualenvs/dd_3k/include/freetype2 -I/usr/local/include -I/usr/include -I. -Iextern/agg24-svn/include -I/home/tcaswell/.virtualenvs/dd_3k/include/python3.4m -c src/_backend_agg_wrapper.cpp -o build/temp.linux-x86_64-3.4/src/_backend_agg_wrapper.o
In file included from src/path_converters.h:8:0,
                 from src/_backend_agg_basic_types.h:11,
                 from src/py_converters.h:18,
                 from src/_backend_agg_wrapper.cpp:2:
src/_backend_agg.h: In instantiation of ‘void RendererAgg::draw_markers(GCAgg&, PathIterator&, agg::trans_affine&, PathIterator&, agg::trans_affine&, agg::rgba) [with PathIterator = py::PathIterator]’:
src/_backend_agg_wrapper.cpp:275:5:   required from here
src/MPL_isnan.h:62:19: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   ( (( MPL_U64(u) & 0x7ff0000000000000LL)  == 0x7ff0000000000000LL)) ? 1:0
                   ^
src/_backend_agg.h:600:21: note: in expansion of macro ‘MPL_notisfinite64’
                 if (MPL_notisfinite64(x) || MPL_notisfinite64(y)) {
                     ^
src/MPL_isnan.h:62:19: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   ( (( MPL_U64(u) & 0x7ff0000000000000LL)  == 0x7ff0000000000000LL)) ? 1:0
                   ^
src/_backend_agg.h:600:45: note: in expansion of macro ‘MPL_notisfinite64’
                 if (MPL_notisfinite64(x) || MPL_notisfinite64(y)) {
                                             ^
src/MPL_isnan.h:62:19: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   ( (( MPL_U64(u) & 0x7ff0000000000000LL)  == 0x7ff0000000000000LL)) ? 1:0
                   ^
src/_backend_agg.h:632:21: note: in expansion of macro ‘MPL_notisfinite64’
                 if (MPL_notisfinite64(x) || MPL_notisfinite64(y)) {
                     ^
src/MPL_isnan.h:62:19: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   ( (( MPL_U64(u) & 0x7ff0000000000000LL)  == 0x7ff0000000000000LL)) ? 1:0
                   ^
src/_backend_agg.h:632:45: note: in expansion of macro ‘MPL_notisfinite64’
                 if (MPL_notisfinite64(x) || MPL_notisfinite64(y)) {
                                             ^
```

but I see them on the ubuntu box too

**Comment by tacaswell** [comment]
This is almost certianly a complier/optimization if I throw in some couts in the nan-removal loop it works, remove them and it does not

```diff
22:55 $ git diff
diff --git a/src/path_converters.h b/src/path_converters.h
index 7755772..1db4f21 100644
--- a/src/path_converters.h
+++ b/src/path_converters.h
@@ -2,7 +2,7 @@
 
 #ifndef __PATH_CONVERTERS_H__
 #define __PATH_CONVERTERS_H__
-
+#include <iostream>
 #include "agg_path_storage.h"
 #include "agg_clip_liang_barsky.h"
 #include "MPL_isnan.h"
@@ -213,15 +213,18 @@ class PathNanRemover : protected EmbeddedQueue<4>
         {
             /* This is the fast path for when we know we have no curves */
             code = m_source->vertex(x, y);
+           std::cout << "in fast path" << std::endl;
 
             if (code == agg::path_cmd_stop ||
                 code == (agg::path_cmd_end_poly | agg::path_flags_close)) {
+               std::cout << "found end" << std::endl;
                 return code;
             }
-
+           std::cout << "x: " << *x << "y: "<< *y << std::endl;
             if (MPL_notisfinite64(*x) || MPL_notisfinite64(*y)) {
                 do {
                     code = m_source->vertex(x, y);
+                   std::cout << "** x: " << *x << "y: "<< *y << std::endl;
                     if (code == agg::path_cmd_stop ||
                         code == (agg::path_cmd_end_poly | agg::path_flags_close)) {
                         return code;

``` 

I will have a PR in soon that fixes this is a quieter way.

**Comment by mdboom** [comment]
Thanks for doing all of the legwork/research on this.  A possible fix is in #4527.

**Comment by jenshnielsen** [comment]
The fix in #4527 makes sense to me. However, perhaps a test based on the example should be added since this seems not to be covered by any tests presently

**Comment by mdboom** [comment]
It is covered by tests -- in fact, building with a gcc 5.1.0 compiler results in test failures on master.  We don't have gcc 5.1.0 on Travis, of course.

**Comment by jenshnielsen** [comment]
Ok great!
