### PR TITLE
Add (color, alpha) tuple as a valid ColorType in typing.py

### PR DESCRIPTION
**Pull request by ksunden**
## PR Summary

Introduced by #24691, merged shortly before #24976

Not totally sold on the name 'RawColorType', but couldn't think of something I like better

Noticed that one of the other type aliases was not documented, so fixed that while I was editing these two files

Tested using:

```python
from matplotlib.typing import ColorType

a: ColorType = "blue"
b: ColorType = (.5, .2, .1)
c: ColorType = (.5, .2, .1, .7)

d: ColorType = ("blue", .8)
e: ColorType = ((.5, .2, .1), .7)
f: ColorType = ((.5, .2, .1, .7), .5)
```

Prior to PR d,e,f are flagged as invalid, but they pass the typechecker after this PR:

```
kyle@plutonium py@edge play $ mypy mypy_mpl.py 
mypy_mpl.py:7: error: Incompatible types in assignment (expression has type "Tuple[str, float]", variable has type "Union[Tuple[float, float, float], Tuple[float, float, float, float], str]")  [assignment]
mypy_mpl.py:8: error: Incompatible types in assignment (expression has type "Tuple[Tuple[float, float, float], float]", variable has type "Union[Tuple[float, float, float], Tuple[float, float, float, float], str]")  [assignment]
mypy_mpl.py:9: error: Incompatible types in assignment (expression has type "Tuple[Tuple[float, float, float, float], float]", variable has type "Union[Tuple[float, float, float], Tuple[float, float, float, float], str]")  [assignment]
Found 3 errors in 1 file (checked 1 source file)
```

```
kyle@plutonium py@edge play $ mypy mypy_mpl.py 
Success: no issues found in 1 source file
```

Raises the valid point of including tests like these in the repo/ci, but probably requires a bit more thought than this particular PR is ready to add initially.

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by timhoffm** [comment]
Maybe SolidColorType instead if RawColorType?

**Comment by ksunden** [comment]
"Solid" would imply to me that there is no alpha, but an RGBA 4-tuple is valid there

**Comment by rcomer** [comment]
`BaseColorType`?

**Comment by ksunden** [comment]
The other option that occurs to me, though it is slightly more complicated, but perhaps in a useful way:

```python
RGBColorType = str | tuple[float, float, float]
RGBAColorType = str | tuple[float, float, float, float] | tuple[RGBColorType, float] | tuple[tuple[float, float, float, float], float]
ColorType = RGBColorType | RGBAColorType
```

Not so happy about the last leg of RGBA needing to be added (not as clean as I would like, but not _too_ bad.

Both need str, not only for named colors (which would actually almost exclusively be the RGB, not RGBA), but also for hex colors (`"#RRGGBB(AA)"`) and while in some sense those are a different "type", we pass them as strings and don't have a good way of telling the typechecker the difference satisfactorily.

(The exception for named colors that have non-opaque alpha is `"none"`, I'm pretty sure all others have no alpha component inherently)

(I wrote it out here with `|` notation, which is py3.10+ but more readable, would have to use `Union[..., ...]` in this context since the type alias is actually potentially evaluated at runtime (not imported by default, but importable; unlike type annotations which are not directly evaluated))

**Review by timhoffm — APPROVED** [review]

File: lib/matplotlib/typing.py [hunk 1]
```diff
@@ -19,7 +19,21 @@
 # The following are type aliases. Once python 3.9 is dropped, they should be annotated
 # using ``typing.TypeAlias`` and Unions should be converted to using ``|`` syntax.
 
-ColorType = Union[tuple[float, float, float], tuple[float, float, float, float], str]
+RGBColorType = Union[tuple[float, float, float], tuple[float, float, float, float], str]
```
Comment (ksunden) [inline lib/matplotlib/typing.py:22]:
```suggestion
RGBColorType = Union[tuple[float, float, float], str]
```

**Comment by ksunden** [comment]
There is no place where we actually use the RGB/RGBA specific types, but string is valid for either, so we _could_ specify if it were relevant.

Essentially I needed _a_ name to organize the thought of "2-tuple of this type plus float alpha"

The original called it "RawColorType" but I didn't like that name and chose to go with something at least semantically meaningful as a distinction.
