### ISSUE TITLE
importing pyplot raises error

### ISSUE THREAD

**Issue by Omnipresent** [matplotlib/matplotlib#5143]
After installing matplotlib I tried importing pyplot but got the error message below:

`**RuntimeError**: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends.`

So I followed this solution: http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

However, now I'm getting this error

`ImportError: No module named '_tkinter'`

Here is the entire stacktrace:

```bash
▶ python
Python 3.5.0 (default, Sep 24 2015, 19:45:12) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhaarat/.virtualenvs/cv3/lib/python3.5/site-packages/matplotlib-1.5.0rc1+83.g39f0136-py3.5-macosx-10.10-x86_64.egg/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/bhaarat/.virtualenvs/cv3/lib/python3.5/site-packages/matplotlib-1.5.0rc1+83.g39f0136-py3.5-macosx-10.10-x86_64.egg/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/bhaarat/.virtualenvs/cv3/lib/python3.5/site-packages/matplotlib-1.5.0rc1+83.g39f0136-py3.5-macosx-10.10-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/Users/bhaarat/.virtualenvs/cv3/lib/python3.5/site-packages/matplotlib-1.5.0rc1+83.g39f0136-py3.5-macosx-10.10-x86_64.egg/matplotlib/externals/six.py", line 90, in __get__
    result = self._resolve()
  File "/Users/bhaarat/.virtualenvs/cv3/lib/python3.5/site-packages/matplotlib-1.5.0rc1+83.g39f0136-py3.5-macosx-10.10-x86_64.egg/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/Users/bhaarat/.virtualenvs/cv3/lib/python3.5/site-packages/matplotlib-1.5.0rc1+83.g39f0136-py3.5-macosx-10.10-x86_64.egg/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 35, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named '_tkinter'
```

**Comment by WeatherGod** [comment]
You need to have the development packages for Tk/Tcl installed prior to
building matplotlib if you want to use the TkAgg backend. Or you can use
one of the other backends such as macosx, qt5agg, or some such.

**Comment by Omnipresent** [comment]
I built matplotlib from the source. Where can I get Tk/Tcl from? Since I have already installed and built matplotlib do I need to reinstall or can I just build and install it again?

**Comment by WeatherGod** [comment]
There should be detailed instructions in the README.osx file in the source
tree. I am not a mac user, so I don't know the details myself. All I know
is that once you get past these initial hurdles, it gets much easier.

**Comment by efiring** [comment]
You are using python from homebrew, correct? I suspect that if you install it using the option --with-tcl-tk, you will have the necessary headers along with everything else.
An alternative is to use the qt4agg backend, which doesn't require anything at mpl build time.  Try
`brew install pyqt --with-python3`.

**Comment by tacaswell** [comment]
attn @jenshnielsen

**Comment by jenshnielsen** [comment]
It works on my version of python from Homebrew. Can you test what the following does.

```python
import _tkinter
```

The problem with the OSX backend is a limitation in virtual env and not in matplotlib or the homebrew python. I really should finish my faq about this at https://github.com/jenshnielsen/matplotlib/blob/799e0fed6336da6db8b70e3b2948f225d513a8fb/doc/faq/virtualenv_faq.rst

**Comment by Omnipresent** [comment]
Sorry for the late reply. 

`import _tkinter` also doesn't work on my end. However, surprisingly, it works on my python2.7

```bash
▶ python
Python 3.5.0 (default, Sep 24 2015, 19:45:12)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named '_tkinter'
>>> exit()
(cv3)
~
▶ deactivate

~
▶ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
>>> exit()
```

**Comment by jenshnielsen** [comment]
Ok it looks like for what ever reason your version of python35 does is not build with tk. It works with my version of python3.5 from homebrew. How did you install python35? 

```
Python 3.5.0 (default, Oct  4 2015, 08:12:28)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
```

**Comment by Omnipresent** [comment]
I installed it using homebrew

```
> ls -al /usr/local/bin/python3
lrwxr-xr-x  1 bhaarat  admin  35 Sep 24 19:45 /usr/local/bin/python3 -> ../Cellar/python3/3.5.0/bin/python3
```

**Comment by Omnipresent** [comment]
I took @efiring advice. I uninstalled python3 and installed it `--with-tcl-tk`

Now I can `import _tkinter` but get an error when import `matplotlib.pyplot`

```bash
▶ python
Python 3.5.0 (default, Nov 23 2015, 18:39:16)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
>>> import matplotlib
>>> import matplotlib.pyplot
ImportError: cannot import name '_tkagg'
```

**Comment by tacaswell** [comment]
Now you have to rebuild mpl against the newly installed tk headers/library
;)

**Comment by Omnipresent** [comment]
:( 

```
code/python/matplotlib  master ✔                                                                                                      59d
▶ python3 setup.py install
In file included from src/_tkagg.cpp:28:
/usr/local/include/tk.h:71:13: fatal error: 'X11/Xlib.h' file not found
#   include <X11/Xlib.h>
            ^
1 error generated.
error: command 'clang' failed with exit status 1
```

**Comment by Omnipresent** [comment]
So, I tried to rebuilt mpl. The build went fine but now when I `import matplotlib.pyplot` I get an error mentioned in https://github.com/matplotlib/matplotlib/issues/2025 and that issue doesn't have a resolution. Does someone know how to resolve this?

```
(cv3)
~
▶ python
Python 3.5.0 (default, Nov 23 2015, 18:39:16)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
objc[24785]: Class TKApplication is implemented in both /usr/local/opt/tcl-tk/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[24785]: Class TKMenu is implemented in both /usr/local/opt/tcl-tk/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[24785]: Class TKContentView is implemented in both /usr/local/opt/tcl-tk/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[24785]: Class TKWindow is implemented in both /usr/local/opt/tcl-tk/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
```

**Comment by jenshnielsen** [comment]
It should not be necessary to build the homebrew python 3 with `--with-tcl-tk` I have the regular build and that works just fine but I think it was broken at some point so it is possible if you have a regular build of python3 from homebrew from a particular period date range that is why it is broken.

The option only toggles between using the newer version of tcl/tk that homebrew ships and the old version that Apple ships. 

Furthermore it looks like there was an issue with the `--with-tcl-tk` which was fixed in homebrew yesterday (the commit is old but it was not merged until yesterday)
https://github.com/Homebrew/homebrew/commit/cff239addef86cc2bdeac6d97bd57992540f2ace
So if you use that option you should probably reinstall.

**Comment by efiring** [comment]
Duplicate of #2025.
