### PR TITLE
FIX: only expect FigureCanvas on backend module if using new style

### LINKED ISSUE #23911: [Bug]: 3.6.0 doesn't interact well with pycharm throwing "backend_interagg" exception
### Bug summary

While using Pycharm and matplotlib 3.6.0 as soon as we import matplotlib, the interpreter crash

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.figure(1)
```

### Actual outcome

```python
    canvas_class = backend_mod.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
```

### Expected outcome

same thing works with version 3.5.2

### Additional information

_No response_

### Operating system

_No response_

### Matplotlib Version

3.6.0

### Matplotlib Backend

module://backend_interagg

### Python version

3.8

### Jupyter version

_No response_

### Installation

_No response_

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Summary

This is to un-break pycharm's backend_interagg

Closes #23911

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

I'm not sure the best way to test this, I guess we need to make a minimal backend that does not have FigureCanvas and try push it through the machinery?  Is it worth the effort?

### CODE REVIEW

**Review by anntzer — APPROVED** [review]

**Review by oscargus — APPROVED** [review]

**Comment by ice1000** [comment]
Is this released?

**Comment by tacaswell** [comment]
No, this will be in 3.6.1 when it is relesaed.

**Comment by ice1000** [comment]
> No, this will be in 3.6.1 when it is relesaed.

Looking forward!

**Comment by davidgilbertson** [comment]
Thanks for moving so quickly on this @tacaswell!
