### ISSUE TITLE
[Bug]: Can't add tools to the toolbar

### ISSUE THREAD

**Issue by Valentin-2002** [matplotlib/matplotlib#28684]
### Bug summary

After testing the toolbar customization in the version 3.9 using the following [code example ](https://matplotlib.org/stable/gallery/user_interfaces/toolmanager_sgskip.html), I'm getting an error, which states that the method add_tool couldn't be found (anymore).

### Code for reproduction

```Python
import matplotlib.pyplot as plt

from matplotlib.backend_tools import ToolBase, ToolToggleBase

plt.rcParams['toolbar'] = 'toolmanager'


class ListTools(ToolBase):
    """List all the tools controlled by the `ToolManager`."""
    default_keymap = 'm'  # keyboard shortcut
    description = 'List Tools'

    def trigger(self, *args, **kwargs):
        print('_' * 80)
        fmt_tool = "{:12} {:45} {}".format
        print(fmt_tool('Name (id)', 'Tool description', 'Keymap'))
        print('-' * 80)
        tools = self.toolmanager.tools
        for name in sorted(tools):
            if not tools[name].description:
                continue
            keys = ', '.join(sorted(self.toolmanager.get_tool_keymap(name)))
            print(fmt_tool(name, tools[name].description, keys))
        print('_' * 80)
        fmt_active_toggle = "{!s:12} {!s:45}".format
        print("Active Toggle tools")
        print(fmt_active_toggle("Group", "Active"))
        print('-' * 80)
        for group, active in self.toolmanager.active_toggle.items():
            print(fmt_active_toggle(group, active))


class GroupHideTool(ToolToggleBase):
    """Show lines with a given gid."""
    default_keymap = 'S'
    description = 'Show by gid'
    default_toggled = True

    def __init__(self, *args, gid, **kwargs):
        self.gid = gid
        super().__init__(*args, **kwargs)

    def enable(self, *args):
        self.set_lines_visibility(True)

    def disable(self, *args):
        self.set_lines_visibility(False)

    def set_lines_visibility(self, state):
        for ax in self.figure.get_axes():
            for line in ax.get_lines():
                if line.get_gid() == self.gid:
                    line.set_visible(state)
        self.figure.canvas.draw()


fig = plt.figure()
plt.plot([1, 2, 3], gid='mygroup')
plt.plot([2, 3, 4], gid='unknown')
plt.plot([3, 2, 1], gid='mygroup')

# Add the custom tools that we created
fig.canvas.manager.toolmanager.add_tool('List', ListTools)
fig.canvas.manager.toolmanager.add_tool('Show', GroupHideTool, gid='mygroup')

# Add an existing tool to new group `foo`.
# It can be added as many times as we want
fig.canvas.manager.toolbar.add_tool('zoom', 'foo')

# Remove the forward button
fig.canvas.manager.toolmanager.remove_tool('forward')

# To add a custom tool to the toolbar at specific location inside
# the navigation group
fig.canvas.manager.toolbar.add_tool('Show', 'navigation', 1)

plt.show()
```

### Actual outcome

File "/Users/valentin2002/Documents/testproject/test_toolbar.py", line 68, in <module>
    fig.canvas.manager.toolbar.add_tool('zoom', 'foo')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'add_tool'

### Expected outcome

The toolbar should be customized as specified in the code example and the plot figure should be redered accordingly.

### Additional information

It worked in the Version 3.6 (didn't test the versions between 3.6 and 3.9), while it isn't working in the current stable version 3.9.

Might the cause be, that the structure of the corresponding code has been changed in the new release and the documentation with the code example hasn't been updated yet?

### Operating system

macOS

### Matplotlib Version

3.9

### Matplotlib Backend

macosx

### Python version

3.12.3

### Jupyter version

not used

### Installation

pip

**Comment by greglucas** [comment]
I think this has to do with the backend you're using. This fails for me with Matplotlib v3.6 with the `macosx` backend as well, so I don't think that functionality has changed there.

If you use the `qtagg` or `tkagg` backends, your example works for me in Matplotlib 3.9.

**Comment by Valentin-2002** [comment]
Thanks, that solved it for me!
