### ISSUE TITLE
_macosx.m fails to compile on Mac OS 10.6.8 Snow Leopard

### ISSUE THREAD

**Issue by fvaccari** [matplotlib/matplotlib#10516]
### Bug report

**Bug summary**

Compilation fails in MacPorts on Snow Leopard with this error message due to code in _macosx.m:

```
:info:build src/_macosx.m:1313: error: ‘for’ loop initial declaration used outside C99 mode
:info:build error: command '/usr/bin/llvm-gcc-4.2' failed with exit status 1

```

**Current statement**

As I see it is currently line 1310 of _macosx.m:
```
for (size_t state_index = 0; state_index < n; state_index++)
```

**Proposed syntax**

This syntax allows for proper compilation, and should not break on more modern systems
```
size_t state_index;
for (state_index = 0; state_index < n; state_index++)
```

**Matplotlib version**

  * Operating system: Mac OS X 10.6.8 Snow Leopard
  * Matplotlib version: py36-matplotlib @2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.4
  * Jupyter version (if applicable):
  * Other libraries: 

Installed with MacPorts 

- 2.4.2

**Comment by tacaswell** [comment]
Is this as new version of osx or an old version?

Could you put in a PR with that change?

**Comment by efiring** [comment]
On 2018/02/17 8:40 AM, Thomas A Caswell wrote:
> Is this as new version of osx or an old version?

Ancient.  It came out in 2009.

**Comment by fvaccari** [comment]
It is an old but well respected OS version, mentioned at the beginning of _macosx.m:

/* Proper way to check for the OS X version we are compiling for, from
   http://developer.apple.com/documentation/DeveloperTools/Conceptual/cross_development */
#if __MAC_OS_X_VERSION_MIN_REQUIRED >= 1060
#define COMPILING_FOR_10_6
#endif

so I believe it should be supported.

I hope I've managed to make my first PR properly:

<https://github.com/matplotlib/matplotlib/pull/10519>

Thanks

Franco

**Comment by tacaswell** [comment]
closed by #10519
