### PR TITLE
DOC: document the issues with overlaying new mpl on old mpl

### LINKED ISSUE #26827: [Bug]: ImportError when using Matplotlib v3.8.0 in Python package tests
### Bug summary

I am encountering an ImportError when attempting to use Matplotlib v3.8.0 in my Python package's tests, specifically when running them with pytest. This issue does not occur with older versions of Matplotlib, such as v3.7.3.

### Code for reproduction

```python
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 23, in <module>
    from matplotlib import _api, cbook, docstring, _preprocess_data
ImportError: cannot import name 'docstring' from 'matplotlib' (/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/__init__.py)
```

### Actual outcome

When running the tests, I receive the following ImportError:

```python
tests/integration/test_cli.py:263: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.local/lib/python3.10/site-packages/pyKVFinder/main.py:214: in cli
    plot_frequencies(frequencies, output_plot)
../../.local/lib/python3.10/site-packages/pyKVFinder/utils.py:952: in plot_frequencies
    import matplotlib.pyplot as plt
../../.local/lib/python3.10/site-packages/matplotlib/pyplot.py:66: in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
../../.local/lib/python3.10/site-packages/matplotlib/figure.py:43: in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
../../.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:58: in <module>
    from mpl_toolkits.mplot3d import Axes3D
/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py:1: in <module>
    from .axes3d import Axes3D
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    """
    axes3d.py, original mplot3d version by John Porter
    Created: 23 Sep 2005
    
    Parts fixed by Reinier Heeres <reinier@heeres.eu>
    Minor additions by Ben Axelrod <baxelrod@coroware.com>
    Significant updates and revisions by Ben Root <ben.v.root@gmail.com>
    
    Module containing Axes3D, an object which can plot 3D objects on a
    2D matplotlib figure.
    """
    
    from collections import defaultdict
    import functools
    import inspect
    import itertools
    import math
    from numbers import Integral
    import textwrap
    
    import numpy as np
    
>   from matplotlib import _api, cbook, docstring, _preprocess_data
E   ImportError: cannot import name 'docstring' from 'matplotlib' (/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/__init__.py)

/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py:23: ImportError
```

### Expected outcome

I expected my tests to run successfully with Matplotlib v3.8.0, just as they did with v3.7.3.

### Additional information

- Has this worked in earlier versions?
It is working in previous versions (eg, v3.7.3).

- Do you know why this bug is happening?
When running the following command to get the Matplotlib Backend: 
```python
import matplotlib; print(matplotlib.get_backend())
```
I got the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/__init__.py", line 1275, in get_backend
    return rcParams['backend']
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/__init__.py", line 759, in __getitem__
    from matplotlib import pyplot as plt
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 23, in <module>
    from matplotlib import _api, cbook, docstring, _preprocess_data
ImportError: cannot import name 'docstring' from 'matplotlib' (/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/__init__.py)
```

### Operating system

Pop!_OS 22.04 LTS

### Matplotlib Version

3.8.0

### Matplotlib Backend

ImportError: cannot import name 'docstring' from 'matplotlib' (/home/ABTLUS/joao.guerra/.local/lib/python3.10/site-packages/matplotlib/__init__.py)

### Python version

3.10.12

### Jupyter version

6.5.1 (Not using Jupyter notebook)

### Installation

pip

### PR DESCRIPTION
**Pull request by tacaswell**
closes #26827

### CODE REVIEW

File: doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst [hunk 1]
```diff
@@ -171,3 +171,18 @@ saved.
...
+
+Following the deprecation of ``pkg_resources.declare_namespace`` in ``setuptools`` 67.3.0,
+``matplotlib.mpl_toolkits`` is now implemented as an implicit namespace, following
+`PEP 420 <https://peps.python.org/pep-0420/>`_.
+
+As a consequence using ``pip`` to install a version of Matplotlib >= 3.8 on top
+of a version of Matplotlib < 3.8 (e.g. via ``pip install --local`` or
+``python -m venv --system-site-packages ...``) will fail because the old
+`matplotlib.mpl_toolkits` files will be found where as the newer files will be
+found for all other modules.  This will result in errors due to the version
```
Comment (jklymak) [inline doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst:187]: Is there anything we can do about this?  eg somehow clean out the old files on pip install, I guess by overwriting them with empty files?  

Or barring that, it would be helpful if we suggested to users what _they_ should do about this.  I'm not even sure `pip uninstall matplotlib` will clean the mpl_toolkits files out.

Comment (tacaswell) [reply doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst:187]: The issue is the "overlaying".  If the old version of Matplotlib is in the venv (and hence the users has write) then pip takes care of itself, but if you are exposed to a read-only set of files then there is nothing we can do.

Even if there was something to do, it would be pip's job not ours.

File: doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst [hunk 2]
```diff
@@ -183,6 +183,10 @@ Following the deprecation of ``pkg_resources.declare_namespace`` in ``setuptools
 As a consequence using ``pip`` to install a version of Matplotlib >= 3.8 on top
 of a version of Matplotlib < 3.8 (e.g. via ``pip install --local`` or
 ``python -m venv --system-site-packages ...``) will fail because the old
-`matplotlib.mpl_toolkits` files will be found where as the newer files will be
+``matplotlib.mpl_toolkits`` files will be found where as the newer files will be
 found for all other modules.  This will result in errors due to the version
 miss-match.
+
+To avoid this issue you need to avoid having multiple versions of Matplotlib
+in different entries of ``sys.path``.   Either uninstall Matplotlib from
```
Comment (jklymak) [inline doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst:191]:
```suggestion
in different entries of ``sys.path``.   Either uninstall Matplotlib
```

File: doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst (hunk 1 above)
Comment (jklymak) [reply doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst:187]: This is still a bit mysterious, and I don't think I am in a low percentile of our user's sophistication in installing python packages, so can we be more clear?  Is this primarily happening when the operating system has packaged matplotlib as part of the distribution (or apt-install etc), and then the user's pip-install doesn't replace mpl-toolkits in the distribution's version of Matplotlib?  If that is the most common case, can we just say something like that, while leaving open the possibility that the installation got crossed other ways.

Comment (QuLogic) [reply doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst:187]: > Is this primarily happening when the operating system has packaged matplotlib as part of the distribution (or apt-install etc), and then the user's pip-install doesn't replace mpl-toolkits in the distribution's version of Matplotlib?

Yes, that is the common (and likely only?) case.

File: doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst [hunk 3]
```diff
@@ -183,6 +183,10 @@ Following the deprecation of ``pkg_resources.declare_namespace`` in ``setuptools
 As a consequence using ``pip`` to install a version of Matplotlib >= 3.8 on top
 of a version of Matplotlib < 3.8 (e.g. via ``pip install --local`` or
 ``python -m venv --system-site-packages ...``) will fail because the old
```
Comment (jklymak) [inline doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst]: Maybe: 
```suggestion
As a consequence using ``pip`` to install a version of Matplotlib >= 3.8 on top
of a version of Matplotlib < 3.8 (e.g. installed using a system package manager 
like ``apt install ...``, or via ``pip install --local`` or 
``python -m venv --system-site-packages ...``) will fail because the old
```

File: doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst [hunk 4]
```diff
@@ -171,3 +171,22 @@ saved.
...
+Following the deprecation of ``pkg_resources.declare_namespace`` in ``setuptools`` 67.3.0,
+``matplotlib.mpl_toolkits`` is now implemented as an implicit namespace, following
+`PEP 420 <https://peps.python.org/pep-0420/>`_.
+
+As a consequence using ``pip`` to install a version of Matplotlib >= 3.8 on top
+of a version of Matplotlib < 3.8 (e.g. via ``pip install --local`` or
+``python -m venv --system-site-packages ...``) will fail because the old
+``matplotlib.mpl_toolkits`` files will be found where as the newer files will be
+found for all other modules.  This will result in errors due to the version
+miss-match.
```
Comment (Mecanerd) [inline doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst:188]:
```suggestion
mismatch.
```

File: doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst [hunk 5]
```diff
@@ -171,3 +171,22 @@ saved.
...
+----------------------------------------------------------------
+
+Following the deprecation of ``pkg_resources.declare_namespace`` in ``setuptools`` 67.3.0,
+``matplotlib.mpl_toolkits`` is now implemented as an implicit namespace, following
+`PEP 420 <https://peps.python.org/pep-0420/>`_.
+
+As a consequence using ``pip`` to install a version of Matplotlib >= 3.8 on top
+of a version of Matplotlib < 3.8 (e.g. via ``pip install --local`` or
+``python -m venv --system-site-packages ...``) will fail because the old
+``matplotlib.mpl_toolkits`` files will be found where as the newer files will be
```
Comment (Mecanerd) [inline doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst:186]:
```suggestion
``matplotlib.mpl_toolkits`` files will be found whereas the newer files will be
```

**Review by ksunden — APPROVED** [review]
I'd tend to agree with some of the review comments that this could be made even more clear, but having it is better than not having it, so going to move forward with what we have. I'd happily consider a reword on this submitted later.
