### ISSUE TITLE
Unable to build matplotlib on macOS

### ISSUE THREAD

**Issue by brodychen** [matplotlib/matplotlib#13609]
### Bug report
I'm having issues building on macOS following the instructions on https://github.com/matplotlib/matplotlib/blob/master/INSTALL.rst#building-on-macos
Dependencies were installed with 
```
#brew install libpng freetype pkg-config
```
**Code for reproduction**

```bash
# python3 -mpip install .
```

**Actual outcome**

```
BUILDING MATPLOTLIB
  matplotlib: yes [3.0.2+1580.g5d56c1c81.dirty]
      python: yes [3.6.0rc1 (v3.6.0rc1:29a273eee9a5, Dec  6 2016, 16:24:13)
                  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]]
    platform: yes [darwin]

OPTIONAL SUBPACKAGES
 sample_data: yes [installing]
       tests: yes [installing]

OPTIONAL BACKEND EXTENSIONS
         agg: yes [installing]
       tkagg: yes [installing; run-time loading from Python Tcl/Tk]
      macosx: yes [installing, darwin]

OPTIONAL PACKAGE DATA
        dlls: no  [skipping due to configuration]

running build
running build_py
copying lib/matplotlib/mpl-data/matplotlibrc -> build/lib.macosx-10.6-intel-3.6/matplotlib/mpl-data
UPDATING build/lib.macosx-10.6-intel-3.6/matplotlib/_version.py
set build/lib.macosx-10.6-intel-3.6/matplotlib/_version.py to '3.0.2+1580.g5d56c1c81.dirty'
running build_ext
building 'matplotlib.ft2font' extension
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -I/Users/brodychen/Library/Python/3.6/lib/python/site-packages/numpy/core/include -Iextern/agg24-svn/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/include -I. -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/checkdep_freetype2.c -o build/temp.macosx-10.6-intel-3.6/src/checkdep_freetype2.o
src/checkdep_freetype2.c:7:9: warning: Compiling with FreeType version 2.9.1. [-W#pragma-messages]
#pragma message("Compiling with FreeType version " \
        ^
1 warning generated.
src/checkdep_freetype2.c:7:9: warning: Compiling with FreeType version 2.9.1. [-W#pragma-messages]
#pragma message("Compiling with FreeType version " \
        ^
1 warning generated.
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -I/Users/brodychen/Library/Python/3.6/lib/python/site-packages/numpy/core/include -Iextern/agg24-svn/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/include -I. -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/ft2font.cpp -o build/temp.macosx-10.6-intel-3.6/src/ft2font.o
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
src/ft2font.cpp:5:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
```

**Expected outcome**
Matplotlib is installed without incident.

**Matplotlib version**

  * Operating system: macOS Mojave
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
Try:

```
export CFLAGS=--stdlib=libc++
export LDLAGS=--stdlib=libc++
```

**Comment by brodychen** [comment]
I tried that, now I'm getting 
```
building 'matplotlib.ft2font' extension
/usr/bin/clang -DNDEBUG -g -fwrapv -O3 -Wall --stdlib=libc++ -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -I/Users/brodychen/Library/Python/3.6/lib/python/site-packages/numpy/core/include -Iextern/agg24-svn/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/include -I. -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/checkdep_freetype2.c -o build/temp.macosx-10.6-intel-3.6/src/checkdep_freetype2.o
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command '/usr/bin/clang' failed with exit status 1```

**Comment by tacaswell** [comment]
This is the import that is missing: http://www.cplusplus.com/reference/algorithm/  That import went in 4 years ago (https://github.com/matplotlib/matplotlib/commit/c1c170209a9def80e31a8fc9559a4349c93ee36d ) to fix compiler errors in visual studio.  

Something seems funny as your initial message says you are using Majove (which is 10.14) but that error message says you need 'OS X better than 10.7'.  My naive guess is that somehow your installation of clang has become confused.

I am optimistic that this is not a systematic OS X issue as our wheels and tests run on OSX on travis (and the tests use brew to get the dependencies).

**Comment by dstansby** [comment]
I suspect this might be related to https://github.com/matplotlib/matplotlib/pull/12407

**Comment by dopplershift** [comment]
I can reproduce the problem by default on my system. Rather than the hard-coded `--stdlib=libc++` arguments as in #12407, I found that building and installing this way works for me:
```sh
MACOSX_DEPLOYMENT_TARGET=10.10 pip install -ve .
```

I also found that this fails:
```sh
MACOSX_DEPLOYMENT_TARGET=10.7 pip install -ve .
```
with the same:
```
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    src/ft2font.cpp:5:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
```

So here's a theory: By default, it's trying to build for an older deployment target, which requires libstdc++. The headers for libstdc++ are no longer installed by newer versions of xcode, so it fails. When specifying a new deployment target, it tries to use libc++ and everything works.

**Comment by dopplershift** [comment]
It works with `MACOSX_DEPLOYMENT_TARGET=10.9` as well. I should note when built that way, `build/` has a `lib.macosx-10.7-x86_64-3.7/` directory.

**Comment by dopplershift** [comment]
So in my case, this is a small problem with conda-forge's Python package. Somewhere in the bowels of `sysconfig`, it's saying Python was built for 10.7, but conda-forge only supports 10.9. If we fix `sysconfig` on conda-forge to set `MACOSX_DEPLOYMENT_TARGET` to `10.9` rather than `10.7`, everything just works.

@brodychen I see your python says 3.6.0rc1. Is this one you built yourself?

**Comment by brodychen** [comment]
I'm actually not sure why my python was set to use 3.6.0rc1 by default. Fixing it to 3.7 resolved the issue. Thanks everyone.

**Comment by bingyao** [comment]
I encountered the exactly the same error when to build matplotlib from source (except that my building process were using `gcc` instead of `clang`). But the building process succeeded after set: 
```
export CFLAGS=--stdlib=libc++
export LDLAGS=--stdlib=libc++
```
as @jklymak shown in his answer.

-----

Following then error info just shown here for reference.

```
Building wheels for collected packages: matplotlib
  Building wheel for matplotlib (setup.py) ... error
  ERROR: Complete output from command /Users/bingyao/anaconda3/envs/mat/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2v/x5zjy_bs3dd__v9r0g3z_ynm0000gn/T/pip-req-build-iuvecjf0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2v/x5zjy_bs3dd__v9r0g3z_ynm0000gn/T/pip-wheel-d7rcyanc --python-tag cp37:
  ERROR: 
  Edit setup.cfg to change the build options; suppress output with --quiet.
  
  BUILDING MATPLOTLIB
    matplotlib: yes [3.1.0+1341.gb1212cab3.dirty]
        python: yes [3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1
                    (tags/RELEASE_401/final)]]
      platform: yes [darwin]
   sample_data: yes [installing]
         tests: no  [skipping due to configuration]
           agg: yes [installing]
         tkagg: yes [installing; run-time loading from Python Tcl/Tk]
        macosx: yes [installing]
  
  running bdist_wheel
  running build
  running build_py
  ...
  ... # lots of creating and copying
  ...
  UPDATING build/lib.macosx-10.7-x86_64-3.7/matplotlib/_version.py
  set build/lib.macosx-10.7-x86_64-3.7/matplotlib/_version.py to '3.1.0+1341.gb1212cab3.dirty'
  running build_ext
  building 'matplotlib.ft2font' extension
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/bingyao/anaconda3/envs/mat/include -arch x86_64 -I/Users/bingyao/anaconda3/envs/mat/include -arch x86_64 -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -I/private/var/folders/2v/x5zjy_bs3dd__v9r0g3z_ynm0000gn/T/pip-req-build-iuvecjf0/.eggs/numpy-1.17.0rc1-py3.7-macosx-10.7-x86_64.egg/numpy/core/include -I/Users/bingyao/anaconda3/envs/mat/include/python3.7m -c src/checkdep_freetype2.c -o build/temp.macosx-10.7-x86_64-3.7/src/checkdep_freetype2.o -I/Users/bingyao/anaconda3/envs/mat/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16
  src/checkdep_freetype2.c:15:9: warning: Compiling with FreeType version 2.10.0. [-W#pragma-messages]
  #pragma message("Compiling with FreeType version " \
          ^
  1 warning generated.
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/bingyao/anaconda3/envs/mat/include -arch x86_64 -I/Users/bingyao/anaconda3/envs/mat/include -arch x86_64 -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -I/private/var/folders/2v/x5zjy_bs3dd__v9r0g3z_ynm0000gn/T/pip-req-build-iuvecjf0/.eggs/numpy-1.17.0rc1-py3.7-macosx-10.7-x86_64.egg/numpy/core/include -I/Users/bingyao/anaconda3/envs/mat/include/python3.7m -c src/ft2font.cpp -o build/temp.macosx-10.7-x86_64-3.7/src/ft2font.o -I/Users/bingyao/anaconda3/envs/mat/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  src/ft2font.cpp:5:10: fatal error: 'algorithm' file not found
  #include <algorithm>
           ^~~~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for matplotlib
  Running setup.py clean for matplotlib
Failed to build matplotlib
```

**Comment by bingyao** [comment]
Another try-and-errors by creating a virtual environment with python's `venv` (instead of `conda`) to install:

This fails with the same error:
```bash
# By using `conda` installed python to create a virtual env
$ path/to/anaconda/bin/python -m venv ~/virtual_envs_with_conda_python
$ source ~/virtual_envs_with_conda_python/bin/activate
$ pip install .
```

And this succeeds:
```bash
# By using standalone installed python (with `homebrew` or other method) to create a virtual env
$ /usr/local/bin/python3 -m venv ~/virtual_envs_with_standalone_python
$ source ~/virtual_envs_with_standalone_python/bin/activate
$ pip install .
```

So,  just like @dopplershift pointed out, I think this problem is _somehow_ related to the `python` binary provided by `conda`, which _somehow_ make `MACOSX_DEPLOYMENT_TARGET` equals to `10.7`. But in my case the `python` binary come from `conda`'s `default` channel (instead of `conda-forge` channel).

Now although I know how to successfully build, but I am still not exactly sure how this error is caused deep down, and how can we fix it beforehand (e.g. by modifying `setup.py` etc.)?

**Comment by dopplershift** [comment]
What does this show on your Python install that fails?
```python
import sysconfig
print(sysconfig.get_config_vars()['MACOSX_DEPLOYMENT_TARGET'])
```
On my working conda install, it prints `10.9`.

There's no magic here, the `sysconfig` module is where things get the information. If your Python says 10.7 is supported, then you should have the older libstdc++ available, otherwise you have a busted build environment.

**Comment by dstansby** [comment]
I'm running across this exact problem again for some reason. The output of the above commands prints:
```python
>>> import sysconfig
>>> print(sysconfig.get_config_vars()['MACOSX_DEPLOYMENT_TARGET'])
10.7
```
for me. As you suggested, doing `MACOSX_DEPLOYMENT_TARGET=10.10 pip install -ve .` solves the problem, still a bit annoying though.

**Comment by dopplershift** [comment]
Where's your python installed from? If conda, can you do `conda list python`?

**Comment by dstansby** [comment]
The relevant line is
```
python                    3.7.3                h359304d_0  
```
, which is from the default channel (if I remember correctly the conda-forge build doesn't present this problem).

**Comment by dopplershift** [comment]
I opened an issue on Anaconda's python feedstock. Hopefully someone can fix it there.

**Comment by dopplershift** [comment]
Looks like the fix has been merged, so next Anaconda python bump should have this fixed.

**Comment by dstansby** [comment]
Fab, thanks a lot!
