### PR TITLE
Use C++ stdlib for isfinite etc.

### LINKED ISSUE #4525: masked arrays broken in py3k + gcc 5.1 on arch linux
This demo http://matplotlib.org/devdocs/examples/pylab_examples/color_by_yvalue.html is broken on python 3.

Only the left most plotted region is shown and happens either with ma arrays or `np.nan` filled arrays (have not started digging yet, I assume the eventually follow the same code path).  Filling with 0 works as expected.

I think bisect on this goes back to the cxx removal but many of the commits in there don't compile on python3 due to a numpy related gcc error so that isn't very helpful.

This smells like a subtle clipping bug.

attn @mdboom @efiring 

The most common compilation error is:

```python
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/home/tcaswell/.virtualenvs/dd_3k/lib/python3.4/site-packages/numpy/core/include -I/home/tcaswell/.virtualenvs/dd_3k/include/freetype2 -I/usr/local/include -I/usr/include -I. -I/home/tcaswell/.virtualenvs/dd_3k/include/python3.4m -c src/ft2font_wrapper.cpp -o build/temp.linux-x86_64-3.4/src/ft2font_wrapper.o
In file included from src/file_compat.h:7:0,
                 from src/ft2font_wrapper.cpp:3:
src/ft2font_wrapper.cpp: In function ‘PyObject* PyFT2Image_as_array(PyFT2Image*, PyObject*, PyObject*)’:
src/ft2font_wrapper.cpp:142:47: error: ‘PyArray_UBYTE’ was not declared in this scope
     return PyArray_SimpleNewFromData(2, dims, PyArray_UBYTE, self->x->get_buffer());
                                               ^
/home/tcaswell/.virtualenvs/dd_3k/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:129:46: note: in definition of macro ‘PyArray_SimpleNewFromData’
         PyArray_New(&PyArray_Type, nd, dims, typenum, NULL, \
                                              ^

```

Going to try rolling back to older versions of numpy te see if that fixes it.

For future reference, the output of bisect:

The first bad commit could be any of:

4a56cdadeb874fd959263fdb7af474c2416457f4
cfbf8d5225ac696cb2c3a8ae096911470074a5f8
339537d58374e8c2f7dd62299a9869d819956937
8dae8186c82f7243b819162d6eb1a64c1afeb379
6e19dac792a42e6cc0f68f2066248a35657673ff
a22596839a7eb31d9700822f2ae09f43c2b765ce
697b3ef37c044787b01344ca166a24d4da58345b
c5ab7474a02f16e75e1bbabcb7af5f7d72f6f847
5204635911f911a48c03ca3cf2f1f70341d396cf
af578f5f35b2d7fef36a35a50d156c027472a816
0624664f857f35583301f55553d28e00a4013770
6d0717930000cafeeecabed900ac1b286a4176da
ba4016014cb4fb4927e36ce8ea429fed47dcb787
d862c4740984433545461ded596d421f48f6b6a7
d8c1d0d5e494465cbc27a639d5337240d84997fe

We cannot bisect more!

Bisect Log:
git bisect start 'master' 'v1.4.3'
a165735 bad Merge pull request #4521 from jkseppan/issue-4475
21f46ff good REL : version 1.4.3

git bisect bad 056ba7a87e5bbd37dbf61a3c27329dc4f5648a54
056ba7a bad MNT : Remove ``NavigationToolbar2QTAgg``

git bisect bad 112f199e26a0ad2047e626f4ceea437196a75909
112f199 bad Merge pull request #3752 from astrofrog/rc_context_exceptions

git bisect good 34ed45af6c693d6951a82619bb669fc5463f4f9d
34ed45a good Merge pull request #3291 from joferkington/lightsource-enhancements

git bisect bad c6f24d3edc787303d631d62c74893bf9bcaaf152
c6f24d3 bad Merge pull request #3665 from jkseppan/fix-gdk-strides

git bisect good 0f4a68d3b75ae5ef192b1c90d876e18ff9de86c5
0f4a68d good Merge pull request #3547 from jkseppan/numpy-deprecation

git bisect bad 7891790ea379d5960fbd61f4667919519456a9a4
7891790 bad Remove reference to PyCXX

git bisect skip 697b3ef37c044787b01344ca166a24d4da58345b
697b3ef skip Restore parallel testing

git bisect skip 6d0717930000cafeeecabed900ac1b286a4176da
6d07179 skip Change how array converter functions are defined

git bisect good 7b206eb0eb150c9b3f8f451977055500c12d92ed
7b206eb good Skip shading of masked array test on numpy 1.6

git bisect skip 8dae8186c82f7243b819162d6eb1a64c1afeb379
8dae818 skip Remove some obsolete TODOs

git bisect skip af578f5f35b2d7fef36a35a50d156c027472a816
af578f5 skip Add .clang-format to repository

git bisect good ea8617d01daa63201d026688efd994423c54659c
ea8617d good fix E201 and E202 pep8 errors

git bisect skip 4a56cdadeb874fd959263fdb7af474c2416457f4
4a56cda skip Fix compilation

git bisect skip d862c4740984433545461ded596d421f48f6b6a7
d862c47 skip Fix Mac compile again

git bisect skip cfbf8d5225ac696cb2c3a8ae096911470074a5f8
cfbf8d5 skip Remove debugging prints

git bisect skip ba4016014cb4fb4927e36ce8ea429fed47dcb787
ba40160 skip Remove use of PyCXX in core C++ extensions

git bisect skip 339537d58374e8c2f7dd62299a9869d819956937
339537d skip Fix curve simplification

git bisect good dbeed94d578c458d31842cd13c04f665155986cb
dbeed94 good Merge pull request #3661 from jenshnielsen/numpy_16_fixes

git bisect skip 6e19dac792a42e6cc0f68f2066248a35657673ff
6e19dac skip Fix segfault on Python 3

git bisect skip 0624664f857f35583301f55553d28e00a4013770
0624664 skip Fix test_hexbin_pickable test

git bisect skip c5ab7474a02f16e75e1bbabcb7af5f7d72f6f847
c5ab747 skip More Python 3 fixes

git bisect skip a22596839a7eb31d9700822f2ae09f43c2b765ce
a225968 skip Documentation

git bisect skip 5204635911f911a48c03ca3cf2f1f70341d396cf
5204635 skip Windows-related fixes, thanks to @cgohlke

git bisect bad d8c1d0d5e494465cbc27a639d5337240d84997fe
d8c1d0d bad Remove usage of old Numpy API

### PR DESCRIPTION
**Pull request by mdboom**
Alternative to #4526.  Fix #4525.

### CODE REVIEW

**Comment by WeatherGod** [comment]
Just for curiosity's sake, I checked the master branch of numpy, and it looks like they got rid of this stuff, too.

**Comment by WeatherGod** [comment]
We should probably have someone check the build on Windows.

**Comment by mdboom** [comment]
Numpy still has it -- they just use a union instead of a cast to get the job done:

https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/npy_math.h#L30

I considered just using Numpy's stuff here, but there is a nameclash with the C++ standard library when you import it, so rather than hacking around that, I decided to just use the C++ standard library.

**Comment by tacaswell** [comment]
I can confirm this works and gets rid of a bunch of complier warnings.

**Comment by jenshnielsen** [comment]
Im :+1: however according to http://en.cppreference.com/w/cpp/numeric/math/isfinite isfinite is a c++ 11 feature so depending on how old compilers we want to target it might be a bit to soon?

**Comment by dopplershift** [comment]
I bet `isfinite` has existed in gcc longer....maybe not in the `std::` namespace though.

**Comment by WeatherGod** [comment]
C99 has isfinite in math.h. Just checked on an ancient linux ppc64 system.

**Comment by mdboom** [comment]
Right -- there's the C99 one, but that seems to get shadowed by the C++ one (at least on gcc 5.1), which is why the numpy ones aren't usable for us.  Anyway, at least we're honing in on a solution.  Finding the optimally portable one may take some work.

**Comment by jenshnielsen** [comment]
I have access to a RHEL 5 system with gcc 4.1. 

Will check there when I get a chance

**Comment by efiring** [comment]
Given that this is needed now  only in C++ code, using the C++ stdlib looks like the cleanest solution.  Historically, the need for this functionality arose in C code--still the case in numpy--hence the use of a cast or union.  Between these two, the union seems like the right way to do it, and presumably it still works fine in numpy.  Even there, it is the legacy of older compilers and standard libraries.

**Comment by efiring** [comment]
@tacaswell, thanks for tracking this down--not a fun way to spend your weekend.  And @mdboom, thanks for finding the right solution.
The only question seems to be whether we need to support compiler/library combinations that are too old to provide `stdlib::isfinite`.  SunOS systems might be in that category.
If we wanted to be extra-conservative, the MPL macros could be retained, but implemented via stdlib when available, and via the numpy code otherwise.
What's a good way of determining whether this level of conservatism is necessary?  One way is to merge the present PR and release it; if anyone trips over it, the worst that can happen is that their attempt to upgrade mpl fails and they fall back to the previous release until we put back the macros.

**Comment by mdboom** [comment]
@efiring: The standard way to support multiple compiler generations is to do some configure-time tests -- where you try to compile some code and if that fails, fallback to a different approach.  Numpy has a few of these in their setup.py based on support for doing that kind of thing in their custom version distutils.  I hate to add that kind of complexity to our build (either by calling into Numpy distutils or copying parts of it), but we may be forced to if this hits enough people to be worth the effort.  

An alternative is to copy the union approach in Numpy -- but use it *always* rather than falling back to system calls if available as Numpy does.  That *may* be slower than the C++ stdlib version -- don't know.

**Comment by tacaswell** [comment]
Aren't there also flags that will identify compliers? We could take the approach of changing this and then special casing as we discover things that don't work?

I have access to some debian ancient machines I can test this on.

**Comment by tacaswell** [comment]
This patch gets rid of 3 test failures for me on gcc 5.1.0.

**Comment by pelson** [comment]
> If we wanted to be extra-conservative

Nope. :wink: 

> One way is to merge the present PR and release it; if anyone trips over it, the worst that can happen is that their attempt to upgrade mpl fails and they fall back to the previous release until we put back the macros.

I like this approach. It keeps us honest. If this affects somebody, what will the error look like? If the error is put verbatim in this PR, the user will find it, understand the problem, and hopefully comment (hello future readers!). At that point, we can look at a more complex solution if necessary.

Merge merge merge :wink: :+1:

**Comment by pelson** [comment]
Thanks @efiring. Did anybody find a compiler which didn't have these definitions? If so, please go ahead and paste the error message into the comments of this PR.

**Comment by jenshnielsen** [comment]
I tested it with GCC 4.1 seems to work
