### ISSUE TITLE
[Bug]: Exception when plotting more than 1000 elements

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#26358]
### Bug summary

`plt.plot(np.arange(N))` fails if N > 1000.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

# works
plt.plot(np.arange(1000))
plt.show()

# raises
plt.plot(np.arange(1001))
plt.show()
```

### Actual outcome

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[51], line 1
----> 1 plt.plot(np.arange(1001
      2                   ))

File ~/git/matplotlib/lib/matplotlib/pyplot.py:3482, in plot(scalex, scaley, data, *args, **kwargs)
   3474 @_copy_docstring_and_deprecators(Axes.plot)
   3475 def plot(
   3476     *args: float | ArrayLike | str,
   (...)
   3480     **kwargs,
   3481 ) -> list[Line2D]:
-> 3482     return gca().plot(
   3483         *args,
   3484         scalex=scalex,
   3485         scaley=scaley,
   3486         **({"data": data} if data is not None else {}),
   3487         **kwargs,
   3488     )

File ~/git/matplotlib/lib/matplotlib/axes/_axes.py:1720, in Axes.plot(self, scalex, scaley, data, *args, **kwargs)
   1718 lines = [*self._get_lines(self, *args, data=data, **kwargs)]
   1719 for line in lines:
-> 1720     self.add_line(line)
   1721 if scalex:
   1722     self._request_autoscale_view("x")

File ~/git/matplotlib/lib/matplotlib/axes/_base.py:2296, in _AxesBase.add_line(self, line)
   2293 if line.get_clip_path() is None:
   2294     line.set_clip_path(self.patch)
-> 2296 self._update_line_limits(line)
   2297 if not line.get_label():
   2298     line.set_label(f'_child{len(self._children)}')

File ~/git/matplotlib/lib/matplotlib/axes/_base.py:2319, in _AxesBase._update_line_limits(self, line)
   2315 def _update_line_limits(self, line):
   2316     """
   2317     Figures out the data limit of the given line, updating self.dataLim.
   2318     """
-> 2319     path = line.get_path()
   2320     if path.vertices.size == 0:
   2321         return

File ~/git/matplotlib/lib/matplotlib/lines.py:1032, in Line2D.get_path(self)
   1030 """Return the `~matplotlib.path.Path` associated with this line."""
   1031 if self._invalidy or self._invalidx:
-> 1032     self.recache()
   1033 return self._path

File ~/git/matplotlib/lib/matplotlib/lines.py:684, in Line2D.recache(self, always)
    679 self._x, self._y = self._xy.T  # views
    681 self._subslice = False
    682 if (self.axes
    683         and len(x) > self._subslice_optim_min_size
--> 684         and _path.is_sorted_and_has_non_nan(x)
    685         and self.axes.name == 'rectilinear'
    686         and self.axes.get_xscale() == 'linear'
    687         and self._markevery is None
    688         and self.get_clip_on()
    689         and self.get_transform() == self.axes.transData):
    690     self._subslice = True
    691     nanmask = np.isnan(x)

AttributeError: module 'matplotlib._path' has no attribute 'is_sorted_and_has_non_nan'
```

### Additional information

The raising code was introduced in #25978. Ping @anntzer 
_No response_

### Matplotlib Version

main branch

**Comment by jklymak** [comment]
This doesn't raise for me.  Did you rebuild?  `is_sorted_and_has_non_nan` is in `_path_wrapper.cpp`.

**Comment by timhoffm** [comment]
Woops. 🐑 Sorry for the noise.
