### ISSUE TITLE
[Bug]: 3.6.0 doesn't interact well with pycharm throwing "backend_interagg" exception

### ISSUE THREAD

**Issue by ucfbrd** [matplotlib/matplotlib#23911]
### Bug summary

While using Pycharm and matplotlib 3.6.0 as soon as we import matplotlib, the interpreter crash

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.figure(1)
```

### Actual outcome

```python
    canvas_class = backend_mod.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
```

### Expected outcome

same thing works with version 3.5.2

### Matplotlib Version

3.6.0

### Matplotlib Backend

module://backend_interagg

### Python version

3.8

**Comment by tacaswell** [comment]
Does this change make it work?

```diff
✔ 14:16:01 $ git diff
diff --git a/lib/matplotlib/pyplot.py b/lib/matplotlib/pyplot.py
index f5c86de126..1e94d90d15 100644
--- a/lib/matplotlib/pyplot.py
+++ b/lib/matplotlib/pyplot.py
@@ -263,7 +263,6 @@ def switch_backend(newbackend):

     backend_mod = importlib.import_module(
         cbook._backend_module_name(newbackend))
-    canvas_class = backend_mod.FigureCanvas

     required_framework = _get_required_interactive_framework(backend_mod)
     if required_framework is not None:
@@ -293,6 +292,8 @@ def switch_backend(newbackend):
     # also update backend_mod accordingly; also, per-backend customization of
     # draw_if_interactive is disabled.
     if new_figure_manager is None:
+        # only try to get the canvas class if have opted into the new scheme
+        canvas_class = backend_mod.FigureCanvas
         def new_figure_manager_given_figure(num, figure):
             return canvas_class.new_manager(figure, num)

```

**Comment by TLCFEM** [comment]
I do not think this PR fixes the problem, after applying the changes, now exception is thrown on Line 185

```
line 185, in _get_required_interactive_framework
    if not hasattr(backend_mod.FigureCanvas, "required_interactive_framework"):
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'. Did you mean: 'FigureCanvasAgg'?
```

**Comment by TLCFEM** [comment]
One more check needs to be added:

```
def _get_required_interactive_framework(backend_mod):
    if not hasattr(backend_mod, 'FigureCanvas') or not hasattr(backend_mod.FigureCanvas, "required_interactive_framework"):
        _api.warn_deprecated(
            "3.6", name="Support for FigureCanvases without a "
            "required_interactive_framework attribute")
        return None
    # Inline this once the deprecation elapses.
    return backend_mod.FigureCanvas.required_interactive_framework
```

**Comment by QuLogic** [comment]
I don't believe the latter check was implemented.

**Comment by TLCFEM** [comment]
> I don't believe the latter check was implemented.

No, it's not.

**Comment by HarmvandenBrand** [comment]
Can confirm this is still an issue with matplotlib 3.6.0 on python 3.10 in PyCharm 2022.2.2

**Comment by nfeliccia** [comment]
Not working on PycharmPro

![image](https://user-images.githubusercontent.com/48567972/192529845-5ebbdf24-5957-4dd3-9c7e-895c82424728.png)
```
import matplotlib.pyplot as plt

pizza, marshmallows = plt.subplots(1, 1)
print(pizza)

```


Error
```

Traceback (most recent call last):
  File "F:\gt_stats_iii\scipy_stats_binom_examples.py", line 8, in <module>
    pizza, marshmallows  = plt.subplots(1, 1)
  File "F:\gt_stats_iii\venv\lib\site-packages\matplotlib\pyplot.py", line 1430, in subplots
    fig = figure(**fig_kw)
  File "F:\gt_stats_iii\venv\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "F:\gt_stats_iii\venv\lib\site-packages\matplotlib\pyplot.py", line 771, in figure
    manager = new_figure_manager(
  File "F:\gt_stats_iii\venv\lib\site-packages\matplotlib\pyplot.py", line 346, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "F:\gt_stats_iii\venv\lib\site-packages\matplotlib\pyplot.py", line 336, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod()) and
  File "F:\gt_stats_iii\venv\lib\site-packages\matplotlib\pyplot.py", line 206, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "F:\gt_stats_iii\venv\lib\site-packages\matplotlib\pyplot.py", line 266, in switch_backend
    canvas_class = backend_mod.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'. Did you mean: 'FigureCanvasAgg'?

Process finished with exit code 1
```

**Comment by mposter1** [comment]
Problem still occurring in PyCharm for me. Still requires FigureCanvas on backend module, running matplotlib 3.8.1. See line 342 of [pyplot.py](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/pyplot.py)

**Comment by ksunden** [comment]
Not having a `FigureCanvas` class as a backend was deprecated in mpl 3.6 and expired in 3.8, it _looks_ like the most recent versions of PyCharm _do_ have it, so perhaps you need to update?

**Comment by QuLogic** [comment]
AFAICT, JetBrains [added those values over a year ago](https://github.com/JetBrains/intellij-community/commit/808410bf8b98a6f91af5612b74271555317f2852), but I cannot tell from the tags exactly what version that means.

**Comment by mposter1** [comment]
Update fixed. Thanks.

**Comment by benyoung-libenyang** [comment]
![屏幕截图 2023-11-10 093046](https://github.com/matplotlib/matplotlib/assets/97272201/415a67ac-52e7-4dd5-aa8e-6bcb1c71ab3c)
maybe you cloud try.

**Comment by oukohou** [comment]
> ![屏幕截图 2023-11-10 093046](https://private-user-images.githubusercontent.com/97272201/281926952-415a67ac-52e7-4dd5-aa8e-6bcb1c71ab3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDk3NTksIm5iZiI6MTcwMjk0OTQ1OSwicGF0aCI6Ii85NzI3MjIwMS8yODE5MjY5NTItNDE1YTY3YWMtNTJlNy00ZGQ1LWFhOGUtNmJjYjFjNzFhYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAxMzA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDJkMzE1MDAzZWUwNGU4ZmVhMGJlM2M1Mjg5NjlkNTUwZWYzYWVlNmJhODYyMWFhYjk4YjcxZmY2YjQ5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAcTESryabZhCef-82Jt1WS8IRWJMD9LfwSjvM5AILk) maybe you cloud try.

great，this fixed my problem.
