### ISSUE TITLE
Matplotlib v1.5.1 apparently not compatible with python-dateutil 2.4.2

### ISSUE THREAD

**Issue by romanrdgz** [matplotlib/matplotlib#6051]
I have Python 2.7.11 64 bits for Windows, which came with Anaconda 2.5.0 bundle.
I started receiving some ImportError in my code:

```
Traceback (most recent call last):
  File "calendar_analizer.py", line 3, in <module>
    import pandas as pd
  File "C:\Anaconda2\lib\site-packages\pandas\__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: lativedelta not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
```
I don't know why it gets cut to "lativedelta", but after some research (during that research I uninstalled and reinstalled using pip pandas, numpy (from a pre-compiled wheel in this case), six, matplotlib and python-dateutils), I finally found that the error comes from a matplotlib import using dateutil.relativedelta.relativedelta:
```
>>> from dateutil.relativedelta import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\dateutil\relativedelta.py", line 3, in <module>
    import calendar
  File "calendar.py", line 1, in <module>
    from risk_graph import plot_risk_graph
  File "risk_graph.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Anaconda2\lib\site-packages\matplotlib\pyplot.py", line 36, in <module>
    from matplotlib.figure import Figure, figaspect
  File "C:\Anaconda2\lib\site-packages\matplotlib\figure.py", line 40, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "C:\Anaconda2\lib\site-packages\matplotlib\axes\__init__.py", line 4, in <module>
    from ._subplots import *
  File "C:\Anaconda2\lib\site-packages\matplotlib\axes\_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "C:\Anaconda2\lib\site-packages\matplotlib\axes\_axes.py", line 22, in <module>
    import matplotlib.dates as _  # <-registers a date unit converter
  File "C:\Anaconda2\lib\site-packages\matplotlib\dates.py", line 129, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: cannot import name relativedelta
```
My current installed versions of matplotlib and python-dateutils are:
```
pip show python-dateutil
---
Metadata-Version: 2.0
Name: python-dateutil
Version: 2.4.2
Summary: Extensions to the standard Python datetime module
Home-page: https://dateutil.readthedocs.org
Author: Yaron de Leeuw
Author-email: me@jarondl.net
License: Simplified BSD
Location: c:\anaconda2\lib\site-packages
Requires: six

pip show matplotlib
---
Metadata-Version: 2.0
Name: matplotlib
Version: 1.5.1
Summary: Python plotting package
Home-page: http://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: BSD
Location: c:\anaconda2\lib\site-packages
Requires: numpy, pyparsing, python-dateutil, pytz, cycler
```
I have read that years ago this problem was due to python-dateutils version, which needed to be 1.5 in order to work with Python 2.7. Nevertheless, it seemed to be fixed for python-dateutils 2.0.

How can I fix this problem?

**Comment by jenshnielsen** [comment]
We are running all our tests agains the latest version of dateutil so it is very unlikely that it doesn't work in general. There is no requirement to use an earlier version of dateutil.

Furthermore I cannot reproduce your issue with dateutil 2.4.2:

```
Python 2.7.11 (default, Dec  5 2015, 14:44:53)
Type "copyright", "credits" or "license" for more information.

IPython 4.1.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import dateutil

In [2]: dateutil.__version__
Out[2]: '2.4.2'

In [3]: from dateutil.relativedelta import relativedelta

In [4]:
```

Looking at your traceback it looks like dateutil is importing calendar i.e. here https://github.com/dateutil/dateutil/blob/master/dateutil/relativedelta.py#L3
and I guess you have a file called calendar.py in the folder that you are running from which is incorrectly imported instead. I suggest renaming that file to something else.

**Comment by romanrdgz** [comment]
You are totally right, I didn't thought calendar.py where a reserved name for a module, but I should have imagined it.

**Comment by WeatherGod** [comment]
To be clear, calendar.py isn't a reserved name for module imports. The
issue is a quirk/feature of python import semantics. A plain simple "import
calendar" (in any module) first checks for a "calendar.py" in the current
working directory, then checks for it in ~/.local/lib/.../site-packages,
then finally in the python's site-packages.

This is why it is a good idea to separate module code from your scripts and
to make your module into an installable package so that you aren't
executing python in a working directory full of .py files.
