### PR TITLE
Fix default return of Collection.get_{cap,join}style

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

If neither are specified at object creation, the default is to be `None`. This broke `get_{cap,join}style` when the enum wrappers were created as they assume the internal value is always an enum value.

```
$ python -c 'from matplotlib.collections import Collection; print(Collection().get_capstyle())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../lib/matplotlib/collections.py", line 643, in get_capstyle
    return self._capstyle.name
AttributeError: 'NoneType' object has no attribute 'name'
$ python -c 'from matplotlib.collections import Collection; print(Collection().get_joinstyle())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../lib/matplotlib/collections.py", line 657, in get_joinstyle
    return self._joinstyle.name
AttributeError: 'NoneType' object has no attribute 'name'
```

This was broken since the initial addition of the enums in #18544, so I'm not sure if it should be backported (minus the typing changes.)

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by ksunden** [comment]
The alternative would be to resolve to the default. As far as I can tell the default is hard coded (here)[https://github.com/matplotlib/matplotlib/blob/2f4f08eff4a3cd57fb6bc3b086e775edf7d19cda/lib/matplotlib/backend_bases.py#L765), so not controlled by rcparam. I suppose backends _could_ override the default? But not convinced that edge case is worth accounting for.

**Comment by QuLogic** [comment]
Yes, this was added in #9523 and, if `None`, defaulted to backend renderer state. Also, #17575 documented this as defaulting to the `patch.{cap,join}style` rcParam, but that doesn't appear to be true. Alternatively we could start defining a default for collections as documented.

Either way, we should probably fix the default and documented default to match.

**Review by ksunden — APPROVED** [review]

**Comment by ksunden** [comment]
Test failure is almost certainly the MacOS/Azure/Tk problem we were having.

**Review by greglucas — APPROVED** [review]
