### ISSUE TITLE
[Bug]: AttributeError: 'AxesSubplot' object has no attribute 'add_text'

### ISSUE THREAD

**Issue by sdbbs** [matplotlib/matplotlib#22093]
### Bug summary

Previously, I had been using `ax.texts.append(annotation)` to control mouseover interaction (appearance of texts) - that seemed to work in 3.4.3, in 3.5.1 it is broken.

### Code for reproduction

```python
import matplotlib
print(matplotlib.__version__)
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
tant = ax.annotate("", xy=(0,0), xytext=(2,2),textcoords="offset points", bbox=dict(boxstyle="round", fc="w"), zorder=10)
print(ax.texts)
ax.texts.append(tant)
print(ax.texts)
```

### Actual outcome

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> print(matplotlib.__version__)
3.5.1
>>> import matplotlib.pyplot as plt
>>> fig, ax = plt.subplots()
>>> tant = ax.annotate("", xy=(0,0), xytext=(2,2),textcoords="offset points", bbox=dict(boxstyle="round", fc="w"), zorder=10)
>>> ax.texts
<Axes.ArtistList of 1 texts>
>>> ax.texts.append(tant)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/_collections_abc.py", line 962, in append
    self.insert(len(self), value)
  File "~/venv_mpl/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1392, in insert
    getattr(self._axes, self._add_name)(item)
AttributeError: 'AxesSubplot' object has no attribute 'add_text'
```

### Expected outcome

From a jupyter notebook with matplotlib 3.4.1, output is:

```
3.4.3
[Text(2, 2, '')]
[Text(2, 2, ''), Text(2, 2, '')]
```

### Operating system

Ubuntu 20.05

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg, module://matplotlib_inline.backend_inline

### Python version

3.8.10

**Comment by jklymak** [comment]
I guess this should still work, but should emit a warning; see:

https://matplotlib.org/devdocs/api/prev_api_changes/api_changes_3.5.0.html#axes-children-are-no-longer-separated-by-type

**Comment by sdbbs** [comment]
Thanks @jklymak  - I took a look at the link, but I still don't understand what should I write instead, to get this to work?

> Formerly, axes.Axes children were separated by Artist type, into sublists such as Axes.lines.

Ok, that is what I had been using previously, I guess, which now breaks.

> Now, the children are no longer separated by type, and the sublist properties are generated dynamically when accessed. Consequently, Artists will now always appear in the correct sublist; ...

I don't really understand this - does it mean that `ax.texts` does not exist, until it's accessed? But isn't `ax.texts` deprecated now? Or is it only for accessing, and only the modification is deprecated - as hinted in:

> Modification of the following sublists is still accepted, but deprecated:

...?

> To add an Artist, use the corresponding Axes.add_* method.

Ok, but in my case, what is `Axes`? When I do:

```
>>> ax
<AxesSubplot:>
```

.... I get that `ax` is `AxesSubplot`, not `Axes`? Or is `AxesSubplot` a subclass of `Axes`, so no worries? If that was the case, then I should be able to call `Axes.add_*`  method, in particular `.add_text`, but as the title says:

```
>>> ax.add_text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AxesSubplot' object has no attribute 'add_text'
```

Could someone help with some concrete advice?

**Comment by jklymak** [comment]
On master, and I assume 3.5.0

```
import matplotlib
print(matplotlib.__version__)
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
tant = ax.annotate("", xy=(0,0), xytext=(2,2),textcoords="offset points", bbox=dict(boxstyle="round", fc="w"), zorder=10)
print(ax.texts)
ax.add_artist(tant)
print(ax.texts)
```

yields

```
3.6.0.dev1116+g72f4046083
<Axes.ArtistList of 1 texts>
<Axes.ArtistList of 2 texts>
```

OTOH I think this is a bug in the redirection logic, because there is no `add_text`, but the deprecation wants you to use it.    Ping @QuLogic...

**Comment by sdbbs** [comment]
Thank you, @jklymak :  

>     ax.add_artist(tant)

... works fine! ( I also ended up sort of discovering this, when I thought again of "*the corresponding `Axes.add_*` method.*", and decided to try if Python shell had tab completion - and tried `ax.add_` and <kbd>TAB</kbd> - and got all the methods listed, that did not include `add_text`)

**Comment by tacaswell** [comment]
@sdbbs Can I ask why you want the same artist to be in the draw tree multiple times?

**Comment by sdbbs** [comment]
@tacaswell : 

> Can I ask why you want the same artist to be in the draw tree multiple times?

Sure - for the OP,  I simply couldn't come up with an example that was simple enough.

What is my actual problem, is that I have a relatively complex plot which I want to be interactive, and since otherwise the plot redraws are sluggish, parts of the plot are "static", some have to be redrawn. One annotation is also one that has to be redrawn, and it's a bit of a fuss setting it up.

Eventually however, I need to also do a full plot redraw, and I've found `ax.clear()` to be excellent and easiest for that - except that also deletes annotations. And since setting up the annotation is a fuss, what I eventually end up doing is:

```
# assign annotation ref to a class propery:

self.myannot = self.ax.annotate(...
# more setup of self.myannot follows ...

# ...

# ... then later, plot needs to be fully redrawn, so we clear all:

self.ax.clear()

# this however, deleted out annotation from the plot;
# however, thanks to the class property, since the class object still lives,
# we still have a reference to the original object in memory,
# so we just need to re-add it to the list:

if version.parse(matplotlib.__version__) < version.parse("3.5.0"):
  self.ax.texts.append(self.myannot)
else:
  self.ax.add_artist(self.myannot)
```

With this, all works for me, without fussing about with instantiating and setting up the annotation again.

**Comment by tacaswell** [comment]
`self.ax.add_artist(self.myannot)` should work on all Matplotlib versions, I think you can get away without version gating.  

Interestingly, this escapes the "can not move to different Axes" logic because it is the same axes.  I would be a little wary of doing this depending on exactly which transform your annotation is using and the details of what `ax.clear()` is going to do to with the various transforms (if it replaces them with new instances this is brittle, if we update them in place then it should work, but depends on us not changing that implementation detail).

Having never seen your code, my knee-jerk suggestion would be to write a function like

```python
def make_me_the_annotation(ax, a, b):
    return ax.annotation(...a, b, ...)
```

-----

Have you looked at https://matplotlib.org/stable/tutorials/advanced/blitting.html ?  If you update the artists in place rather than re-construct them from scratch you should be able to get a bit more performance as well.
