### ISSUE TITLE
del os.link in setup.py is breaking Python 3.8 builds

### ISSUE THREAD

**Issue by jdemeyer** [matplotlib/matplotlib#14580]
### Bug report

**Bug summary**

The line `del os.link` in the `setup.py` of matplotlib-2.2.4 is breaking installs with Python 3.8b1.

**Code for reproduction**

```
pip3 install 'matplotlib==2.2.4'
```

**Actual outcome**

```
[...lots of output skipped...]
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-747fdrmo/matplotlib/setup.py", line 304, in <module>
      distrib = setup(
    File "/usr/local/src/sage-config/local/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/src/sage-config/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-747fdrmo/matplotlib/setup.py", line 141, in run
      return BuildExtCommand.run(self)
    File "/usr/local/src/sage-config/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/usr/local/src/sage-config/local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/local/src/sage-config/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/src/sage-config/local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
      ext.sources = self.cython_sources(ext.sources, ext)
    File "/usr/local/src/sage-config/local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 264, in cython_sources
      extension.include_dirs = list(extension.include_dirs)
    File "/tmp/pip-install-747fdrmo/matplotlib/setupext.py", line 1047, in __get__
      result = obj._hooks[self._name]() + result
    File "/tmp/pip-install-747fdrmo/matplotlib/setupext.py", line 1067, in include_dirs_hook
      import numpy
    File "/tmp/pip-install-747fdrmo/matplotlib/.eggs/numpy-1.16.4-py3.8-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
      from . import core
    File "/tmp/pip-install-747fdrmo/matplotlib/.eggs/numpy-1.16.4-py3.8-linux-x86_64.egg/numpy/core/__init__.py", line 40, in <module>
      from . import multiarray
    File "/tmp/pip-install-747fdrmo/matplotlib/.eggs/numpy-1.16.4-py3.8-linux-x86_64.egg/numpy/core/multiarray.py", line 12, in <module>
      from . import overrides
    File "/tmp/pip-install-747fdrmo/matplotlib/.eggs/numpy-1.16.4-py3.8-linux-x86_64.egg/numpy/core/overrides.py", line 8, in <module>
      from numpy.compat._inspect import getargspec
    File "/tmp/pip-install-747fdrmo/matplotlib/.eggs/numpy-1.16.4-py3.8-linux-x86_64.egg/numpy/compat/__init__.py", line 14, in <module>
      from . import py3k
    File "/tmp/pip-install-747fdrmo/matplotlib/.eggs/numpy-1.16.4-py3.8-linux-x86_64.egg/numpy/compat/py3k.py", line 15, in <module>
      from pathlib import Path, PurePath
    File "/usr/local/src/sage-config/local/lib/python3.8/pathlib.py", line 391, in <module>
      class _NormalAccessor(_Accessor):
    File "/usr/local/src/sage-config/local/lib/python3.8/pathlib.py", line 415, in _NormalAccessor
      link_to = os.link
  AttributeError: module 'os' has no attribute 'link'
```
**Expected outcome**

```
Successfully installed matplotlib-2.2.4
```

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 2.2.4
  * Python version: 3.8.0b1

```
pip3 install 'matplotlib==2.2.4'
```

**Comment by dstansby** [comment]
I'm not sure whether there is a plan to formally support Matplotlib `2.2.x` on Python 3.8, especially given that we end support at the end of this year. If you would like to make a PR with a fix however, I'm sure it would be welcome.

**Comment by jdemeyer** [comment]
PR at #14582

**Comment by anntzer** [comment]
closed by #14582.

**Comment by FDesnoyer** [comment]
Hello, I'm a newbie here but I'm also both a python and matplotlib user, does everything I'm reading here mean that I should keep with 3.7 to keep using matplotlib?
I'm a teacher in France and we teach students to use python with matplotlib, it would soon become a problem if we couldn't use matplotlib anymore.
Have a nice day
F.D.

**Comment by anntzer** [comment]
Matplotlib 3 should work fine with Py3.8 (except that there's no wheels available yet).

**Comment by FDesnoyer** [comment]
Thanks anntzer, I was scared but almost sure that matplotlib wouldn't be totally deprecated.
F.D.
