### ISSUE TITLE
CartoPy code gives attribute error

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#11966]
The following code:
```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

proj = ccrs.LambertConformal()
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1, projection=proj)
ax.set_global()
ax.coastlines()
plt.show()
```
gives a traceback with 3.0.0rc2:
```pytb
Traceback (most recent call last):
  File "/Users/rmay/miniconda3/envs/py36/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1972, in <module>
    matplotlib.axes._subplots._subplot_classes[GeoAxes] = GeoAxesSubplot
AttributeError: module 'matplotlib.axes._subplots' has no attribute '_subplot_classes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_cartopy.py", line 6, in <module>
    ax = fig.add_subplot(1, 1, 1, projection=proj)
  File "/Users/rmay/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/figure.py", line 1352, in add_subplot
    self, *args, **kwargs)
  File "/Users/rmay/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/projections/__init__.py", line 83, in process_projection_requirements
    projection_class, extra_kwargs = projection._as_mpl_axes()
  File "/Users/rmay/miniconda3/envs/py36/lib/python3.6/site-packages/cartopy/crs.py", line 148, in _as_mpl_axes
    import cartopy.mpl.geoaxes as geoaxes
  File "/Users/rmay/miniconda3/envs/py36/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1974, in <module>
    matplotlib.axes._subplot_classes[GeoAxes] = GeoAxesSubplot
AttributeError: module 'matplotlib.axes' has no attribute '_subplot_classes'
```
On 2.2.3 (and many versions before) it works fine.

**Comment by tacaswell** [comment]
Caused by #11195 (attn @anntzer @jklymak @timhoffm )

We should probably use LRU + restore the cache(s)?

**Comment by jklymak** [comment]
Do we need a public API for _subplot_classes?

**Comment by anntzer** [comment]
It's been fixed a while ago: https://github.com/SciTools/cartopy/commit/b331ddd859673fe65f2ffe84570376743aecd22a

**Comment by tacaswell** [comment]
We should put the private API back for a version or two to un-break old versions of cartopy (at least until they get a release with that fix out).

**Comment by dopplershift** [comment]
And we should use "private" in quotes here because IIRC, some of this stuff went in originally to support CartoPy. (Not positive it's this stuff, though.)

**Comment by anntzer** [comment]
Feel free to revert the PR as needed (ping me on it though so that I resubmit it for 3.1 :p or better only revert it on the 3.0 branch...).

**Comment by QuLogic** [comment]
@pelson I think it's time for a new release...

**Comment by anntzer** [comment]
Idea discussed on the call:
Reintroduce the dict as do-nothing (to avoid breaking cartopy).
Modify subplot_class_factory to do something like
```
@functools.lru_cache(None)
def subplot_class_factory(axes_class=None):
    if axes_class is None:
        axes_class = Axes
    try:
        # Avoid creating two different instances of GeoAxesSubplot...
        # Only a temporary backcompat fix.
        return next(cls for cls in SubplotBase.__subclasses__()
                    if cls.__bases__ == (SubplotBase, axes_class))
    except StopIteration:
        return type("%sSubplot" % axes_class.__name__,
                    (SubplotBase, axes_class),
                    {'_axes_class': axes_class})
```
