### ISSUE TITLE
[Bug]: `matplotlib.cm.get_cmap()` missing

### ISSUE THREAD

**Issue by jsolbrig** [matplotlib/matplotlib#28349]
### Bug summary

As of matplotlib v3.9, it appears that `matplotlib.cm.get_cmap()` is missing. It is still available on `matplotlib.pyplot.get_cmap()`, though.

`matplotlib.cm.get_cmap()` [is still shown in the documentation](https://matplotlib.org/devdocs/api/cm_api.html#matplotlib.cm.ColormapRegistry.get_cmap) and I would be surprised if this change was made without some kind of deprecation warning.

### Code for reproduction

```Python
In [1]: from matplotlib import pyplot, cm

In [2]: pyplot.get_cmap('gray')
Out[2]: <matplotlib.colors.LinearSegmentedColormap at 0x7f6b2c7303d0>

In [3]: cm.get_cmap('gray')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 cm.get_cmap('gray')

AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```

### Actual outcome

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 cm.get_cmap('gray')

AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'

### Expected outcome

Should return the `gray` colormap.

### Additional information

This works in matplotlib <3.9 and is still shown in the documentation. It is kind of odd that this function is available from two locations, though.

### Operating system

Any

### Matplotlib Version

3.9.0

### Matplotlib Backend

agg

### Python version

3.11.9

### Installation

pip

**Comment by greglucas** [comment]
Duplicate of https://github.com/matplotlib/matplotlib/issues/28317

This was marked with a deprecation and in 3.8.4 I get the following:
```python
>>> matplotlib.cm.get_cmap("gray")
<stdin>:1: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
```

**Comment by tacaswell** [comment]
We are seeing multiple reports that the warnings in 3.8 were not seen.  We should sort out why and consider putting the API in a micro release with a more visible warning (at maybe a custom `AttributeError` that gives more context?).
